Hello,<br />
<br /><br />
Your new account was created:
<br />If you don't yet know your password please visit the <a href="<?php echo $this->url('forgot-password'); ?>">Forgot Password</a> page to set one up.
<br /><br />
Email: <?php echo $user_data['email']; ?><br />
<br /><br />
You can log into your account by going to:<br />
<a href="<?php echo $this->ServerUrl($this->url('login')); ?>"><?php echo $this->url('login'); ?></a>

<?php //echo $this->partial('partials/footer'); ?>