<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About User Roles</div>
</div>
<p>
User roles are what determines what users can and, more importantly, can't do. Each user group can have it's own set of rules and permissions
that are then attached to a user. 

<br /><br />This allows for quite a bit of customization for maximum security and, if necessary, segregation between
users.
</p>

<h4>Actions</h4>

<p>
		<?php echo $this->InteractIcon('add', 'Add Project');?> Add User Roles
		<br /><?php echo $this->InteractIcon('pencil', 'Edit');?> Edit User Roles
		<br /><?php echo $this->InteractIcon('cross', 'Delete');?> Remove User Roles<br />
	
</p>