<?php 
$form = $this->form;
$form->setAttribute('id', 'proj_form');
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
<input type="hidden" name="start_date_default" id="start_date_default" value="<?php echo date('Y-m-d'); ?>" />
<input type="hidden" name="end_date_default" id="end_date_default" value="<?php echo date('Y-m-d'); ?>" />
<?php 
if($this->id > 0)
	echo '<input type="hidden" value="'.$this->id.'" name="id" />';
?>
<div id="form_tabs">
	<ul>

		<li><a href="#general">General</a></li>
		<li><a href="#dates">Dates</a></li>
	</ul>
	<div id="general">
	
		<p>
			<label for="name">Name</label>
					<?php $name = $form->get('name'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="company_id">Company</label>
			<?php $company_id = $form->get('company_id'); echo $this->formRow($company_id); ?>
		</p>
		
		<p>
			<label for="status">Status</label>
			<?php $status = $form->get('status'); echo $this->formRow($status); ?>
			
		</p>
		
		<p>
			<label for="priority">Priority</label>
			<?php $field = $form->get('priority'); echo $this->formRow($field); ?>
		</p>
		
		<p>
			<label for="type">Type</label>
			<?php $field = $form->get('type'); echo $this->formRow($field); ?>
		</p>								
		
		<p>
			<label for="description">Description</label>
			<?php $field = $form->get('description'); echo $this->formRow($field); ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>			
	
	</div>
	
	<div id="dates">
	
		<p>
			<label for="start_date">Start Date</label>
			<?php $field = $form->get('start_date'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="end_date">End Date</label>
			<?php $field = $form->get('end_date'); echo $this->formRow($field); ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" id="proj_submit"/>
		</p>		
	
	</div>
</div>
<?php echo $this->ConfirmPageUnload('#proj_form')?>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
$.validator.setDefaults({
	//submitHandler: function() { alert("submitted!"); }
});

$().ready(function() {

	$("#proj_form").validate({
		rules: {
			name: "required",
			company_id: "required"
		},
		messages: {
			name: "Please enter a project name",
			company_id: "Please select a company"
		}
	});

});

</script>