<ul class="nav nav-tabs">
    <li class="<?php echo ($this->section == 'view_users' ? 'active"' : '') ; ?>"><a href="<?php echo $this->url('manage_users', array('section' => 'general')); ?>"><?php echo $this->_('users', 'app'); ?></a></li>
    <li class="<?php echo ($this->section == 'manage_roles' ? 'active"' : '') ; ?>"><a href="<?php echo $this->url('manage_roles'); ?>"><?php echo $this->_('roles', 'app'); ?></a></li>
</ul>  

<br />