<?php 

?>
<h3>Lorem ipsum dolor</h3>
<ul>
<li>
<img src="/images/icons/home_32.png" alt="Home" width="32" height="32" class="png_bg" /> <a href="#">Morbi lacinia lacus</a><br />
<p>Integer ornare dapibus nulla vitae.</p>
</li>
<li>
<img src="/images/icons/user_32.png" alt="Users" width="32" height="32" class="png_bg" /> <a href="#">Nam ante sapien</a><br />
<p>Maecenas eleifend laoreet ipsum</p>
</li>
<li class="last">
<img src="/images/icons/chart_32.png" alt="Stats" width="32" height="32" class="png_bg" /> <a href="#">Etiam feugiat ornare</a><br />
<p>Sed id quam in urna.</p>
</li>
</ul>

<h3>Praesent cursus</h3>
<ul>
<li>
<img src="/images/icons/search_32.png" alt="" width="32" height="32" class="png_bg" /> 
<a href="#">Morbi lacinia lacus</a><br />
<p>Integer ornare dapibus nulla vitae.</p>
</li>
<li>
<img src="/images/icons/tools_32.png" alt="Settings" width="32" height="32" class="png_bg" /> 
<a href="#">Nam ante sapien</a><br />
<p>Maecenas eleifend laoreet ipsum</p>
</li>
<li class="last">
<img src="/images/icons/email_32.png" alt="Mail" width="32" height="32" class="png_bg" /> 
<a href="#">Etiam feugiat ornare</a><br />
<p>Sed id quam in urna.</p>
</li>
</ul>

<h3>Aliquam consequat</h3>
<ul>
<li>
<img src="/images/icons/newspaper_32.png" alt="" width="32" height="32" class="png_bg" /> 
<a href="#">Morbi lacinia lacus</a><br />
<p>Integer ornare dapibus nulla vitae.</p>
</li>
<li>
<p><img src="/images/icons/comment_32.png" alt="Comments" width="32" height="32" class="png_bg" /> 
<a href="#">Nam ante sapien</a><br />
Maecenas eleifend laoreet ipsum</p>
</li>
<li class="last">
<img src="/images/icons/info_button_32.png" alt="Info" width="32" height="32" class="png_bg" /> 
<a href="#">Etiam feugiat ornare</a><br />
<p>Sed id quam in urna.</p>
</li>
</ul>

<h3>Dapibus Nulla</h3>
<ul>
<li>
<img src="/images/icons/basket_32.png" alt="Basket" width="32" height="32" class="png_bg" /> 
<a href="#">Morbi lacinia lacus</a><br />
<p>Integer ornare dapibus nulla vitae.</p>
</li>
<li>
<p><img src="/images/icons/clock_32.png" alt="Clock" width="32" height="32" class="png_bg" /> 
<a href="#">Nam ante sapien</a><br />
Maecenas eleifend laoreet ipsum</p>
</li>
<li class="last">
<img src="/images/icons/lightbulb_32.png" alt="Bulb" width="32" height="32" class="png_bg" /> 
<a href="#">Etiam feugiat ornare</a><br />
<p>Sed id quam in urna.</p>
</li>
</ul>      
