<table cellpadding="0" cellspacing="0" class="<?php echo ($this->tableclass) ? $this->tableclass : 'tablesorter'; ?>" id="<?php echo ($this->tableid) ? $this->tableid : 'moji_task_assign'; ?>">
	<thead>
		<tr>
			<th height="10">Assigned To</th>
			<th>Assigned By</th>
			<th>Comment</th>			
			<th>When</th>
		</tr>
	</thead>

	<tbody>
		<?php
		$i = 0;
		foreach($this->assignment_history as $history)
		{
			$assigned_by = array(
							'id' => $history['assigned_by'], 
							'first_name' => $history['by_first_name'], 
							'last_name' => $history['by_last_name']
			);
			
			$assigned_to = array(
							'id' => $history['assigned_to'], 
							'first_name' => $history['to_first_name'], 
							'last_name' => $history['to_last_name']
			);
		?>		
		<tr>
			<td><?php echo ($history['assigned_to'] == 0 ? 'No One' : $this->MakeLink('user', $assigned_to)); ?></td>
			<td><?php echo $this->MakeLink('user', $assigned_by); ?></td>
			<td><?php echo ($history['comments'] == '' ? 'N/A' : $this->Truncate($history['comments']));?></td>
			<td><?php echo $this->RelativeDate($history['created_date']); ?></td>
		</tr>
		<?php 
		}
		?>
	</tbody>
</table>
