<?php 
$form = $this->form;
$form->setAttribute('id', 'task_form');
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>	
<input type="hidden" name="start_date_default" id="start_date_default" value="<?php echo date('Y-m-d'); ?>" />
<input type="hidden" name="end_date_default" id="end_date_default" value="<?php echo date('Y-m-d'); ?>" />
<?php 
if($this->id > 0)
{
	echo '<input type="hidden" value="'.$this->id.'" name="id" />';
} elseif($this->project_data) {
	echo '<input type="hidden" value="'.$this->project_data['id'].'" name="project_id" />';
}
?>
<div id="form_tabs">
	<ul>

		<li><a href="#general">General</a></li>
		<li><a href="#details">Details</a></li>
	</ul>
	<div id="general">
	
		<p>
			<label for="name">Name</label>
			<?php $name = $form->get('name'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="project_id">Project</label>
			<a href="<?php echo $this->url('projects/view', array('project_id' => $this->project_data['id'])); ?>"><?php echo $this->project_data['name']; ?></a>
			
		</p>
		
		<p>
			<label for="assigned_to">Assigned To</label>
			<?php $name = $form->get('assigned_to'); echo $this->formRow($name); ?>
			
		</p>
		
		<p style="display: none" id="assignment_comment">
			<label for="assign_comment">Assignment Comment</label>
			<?php $name = $form->get('assign_comment'); echo $this->formRow($name); ?>
		</p>				
		
		<p>
			<label for="status">Status</label>
			<?php $name = $form->get('status'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="priority">Priority</label>
			<?php $name = $form->get('priority'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="type">Type</label>
			<?php $name = $form->get('type'); echo $this->formRow($name); ?>
			
		</p>																	
		
		<p>
			<label for="description">Description</label>
			<?php $name = $form->get('description'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>				
	
	</div>
	
	<div id="details">
	
		<p>
			<label for="start_date">Start Date</label>
			<?php $name = $form->get('start_date'); echo $this->formRow($name); ?>
			<?php $name = $form->get('start_hour'); echo $this->formRow($name); ?>
			<?php $name = $form->get('start_minute'); echo $this->formRow($name); ?>
			
		</p>

		<p>
			<label for="end_date">End Date</label>
			<?php $name = $form->get('end_date'); echo $this->formRow($name); ?>
			<?php $name = $form->get('end_hour'); echo $this->formRow($name); ?>
			<?php $name = $form->get('end_minute'); echo $this->formRow($name); ?>
			
		</p>
		
		<p>
			<label for="progress">Progress</label>
			<?php $name = $form->get('progress'); echo $this->formRow($name); ?>
			 % 
		</p>		
		
		<p>
			<label for="duration">Expected Duration</label>
			<?php $name = $form->get('duration'); echo $this->formRow($name); ?>
			hours 
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>				
	
	</div>

</div>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
var def_assign = '<?php echo ($this->task_data['assigned_to'] ? $this->task_data['assigned_to'] : 0); ?>';
jQuery(document).ready(function($){
	$("#assigned_to").change(function(){
		//$("#assignment_comment").show();
		var new_assign = $("#assigned_to").val();
		if(new_assign == def_assign || new_assign == 0)
		{
			$("#assignment_comment").hide();
		}
		else
		{
			$("#assignment_comment").show();
		}
	});

	$("#task_form").validate({
		rules: {
			name: "required"
		},
		messages: {
			name: "Please enter a task name"
		}
	});	
});
</script>
<?php echo $this->ConfirmPageUnload('#task_form')?>