<?php $this->headTitle()->append( $this->_('add_ip_address', 'app') )->append( $this->_('admin', 'app') ); ?>
<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('admin', 'cp'); ?> <small><?php echo $this->_('settings', 'cp'); ?></small></h1>
    </div>
      <div class="row">
        <div class="col-sm-3 col-md-3 sidebar">
            <?php echo $this->render('cp/global/_sidebar'); ?>
      </div>
      <div class="col-sm-9 col-md-9">
       <h2><?php echo $this->_('add_ip_address', 'app'); ?></h2>
       <?php echo $this->render('cp/settings/partials/_tabs'); ?>
      
<?php 
$options = array('form' => $this->form, 'form_action' => $this->url('manage_ips/add'));
echo $this->partial('partials/form', $options); 
?>

              
      </div>

</div> 

</div>