<div class="attention png_bg"><?php echo $this->_('ip_locker_enabled', 'pm') ?></div>
<p><?php echo $this->_('ip_locker_enabled_allow_self_message', 'pm') ?></p>

<?php 
$form = $this->form;
$form->setAttribute('id', 'allow_self_ip_form');
$form->setAttribute('action', $this->form_action);
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
<?php 
if($this->id > 0)
	echo '<input type="hidden" value="'.$this->id.'" name="id" />';
?>
		
		<p>
			<input type="submit" class="submit" value="Verify Account" />
		</p>			

<?php echo $this->ConfirmPageUnload('#allow_self_ip_form')?>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
jQuery(document).ready(function($){
	$("#allow_self_ip_form").validate({
		rules: {
			email: {
				required: true,
				email: true
			},
		},
		messages: {
			email: {
				required: "Please enter an email",
				email: "Please enter a valid email address"
			},
		}
	});	
	$.validator.setDefaults({
		submitHandler: function() { return confirm("submitted!"); }
	});	
});
</script>