<div class="content_headers" style="padding-top:0px;">
	<div class="admin_header">Enable Ip Locker</div>	
</div>
<?php if(!$this->ajax_mode): ?>
<div class="back_link_content">
	<a href="<?php echo $this->url('ips'); ?>" title="Back to Ip">
		Back to Ips
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to Ip');?></div>
</div>	
<br clear="all" />
<?php endif; ?>

	<?php if($this->ip_block_enabled != '1'):?>
	<div class="attention png_bg">
		Are you sure you want to enable the Ip Locker?
	</div>
	<?php else: ?>
	<div class="fail png_bg">
		Are you sure you want to disable the Ip Locker?
	</div>
	<?php endif;?>
<p>
<?php 
$form = $this->form;
$form->setAttribute('id', 'ip_form');
$form->setAttribute('action', $this->url('ips/enable'));
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
	<?php $field = $form->get('confirm'); echo $this->formRow($field); ?> <?php $field = $form->get('fail'); echo $this->formRow($field); ?>
<?php echo $this->form()->closeTag() ?>
</p>