<div class="content_headers" style="padding-top:0px;">
	<div class="admin_header">Remove Ip Address</div>	
</div>
<?php if(!$this->ajax_mode): ?>
<div class="back_link_content">
	<a href="<?php echo $this->url('ips/view', array('ip_id' => $this->ip['id'])); ?>" title="Back to Ip">
		Back to Ip
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to Ip');?></div>
</div>	
<br clear="all" />
<?php endif; ?>

<?php if($this->deny): ?>
<div class="fail png_bg">
You can't delete your Ip address while ip blocking is enabled.
</div>

<?php else: ?>
<div class="attention png_bg">
Are you sure you want to remove the Ip Address <?php echo $this->ip['ip_raw']?>? This can not be undone...
</div>
<p>
<?php 
$form = $this->form;
$form->setAttribute('id', 'ip_form');
$form->setAttribute('action', $this->url('ips/remove', array('ip_id' => $this->ip['id'])));
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
	<?php $field = $form->get('confirm'); echo $this->formRow($field); ?> <?php $field = $form->get('fail'); echo $this->formRow($field); ?>
<?php echo $this->form()->closeTag() ?>
</p>
<?php endif; ?>