
<form action="<?php echo $this->escape($this->form->getAction()); ?>" 
method="<?php echo $this->escape($this->form->getMethod()) ?>" enctype="<?php echo $this->escape($this->form->getEnctype()); ?>">

<p>
	<label for="revision">Revision</label>
<?php foreach($this->file_revisions As $revision): ?>
	<div class="revision_images">
		<div class="revision_image_border_def">
			<img id="rev_<?php echo $revision['id']; ?>" class="revision_image" src="<?php echo $this->url(array('module' => 'pm','controller'=>'files','action'=>'preview-revision', 'id' => $revision['id'], 'view-type' => 'html', 'view-size' => 'tb'), null, TRUE); ?>" />
		</div>
	</div>
	<script>
		$('#rev_<?php echo $revision['id']; ?>').click(
			function(){
				$('.revision_images div').removeClass().addClass('revision_image_border_def');
				$(this).parent().removeClass().addClass('revision_image_border');
				$('#review_revision').val('<?php echo $revision['id']; ?>');
			}
		);
	
	</script>
<?php endforeach; ?>
<input type="hidden" value="<?php echo $this->file_revisions['0']['id']; ?>" id="review_revision" name="review_revision" />
</p>

<br clear="all" />
<p>
	<label for="review">Review</label>
	<?php echo $this->form->review; ?>
</p>

<p>
	<input type="submit" class="submit" value="Submit" />
</p>
</form>