<?php 
$form = $this->form;
$form->setAttribute('id', 'file_form');
$form->setAttribute('action', $this->form_action);
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');

if($file_errors)
{
	foreach($file_errors AS $key => $error)
	{
		$error = ($key == 'fileUploadErrorNoFile' ? 'A file is required' : $error);
		echo '<div class="fail canhide png_bg">'.$error.'</div>';
	}
}

echo $this->formRow($csrf);
?>
<?php 
if($this->id > 0)
	echo '<input type="hidden" value="'.$this->id.'" name="id" />';
?>
<?php if($this->file_field): ?>
<p>
	<label for="file">File</label>
	<?php $name = $form->get('file_upload'); echo $this->formRow($name); echo $this->formElementErrors($name); ?>
</p>
<?php endif; ?>

<p>
	<label for="name">Name</label>
	<?php $name = $form->get('name'); echo $this->formRow($name); ?>
</p>

<p>
	<label for="status">Status</label>
	<?php $name = $form->get('status'); echo $this->formRow($name); ?>
</p>

<?php if($this->company_data): ?>
<p>
	<label for="company_id" id="companies">Company</label>
	<a href="<?php echo $this->url('companies/view', array('company_id'=> $this->company_data['id'])); ?>" target="_parent"><?php echo $this->company_data['name']; ?></a>
	<input type="hidden" name="company_id" value="<?php echo $this->company_data['id']; ?>" />
</p>
<?php endif; ?>

<?php if($this->project_data): ?>
<p>
	<label for="project_id">Project</label>
	<a href="<?php echo $this->url('projects/view', array('project_id' => $this->project_data['id'])); ?>"><?php echo $this->project_data['name']; ?></a>
	<input type="hidden" name="project_id" value="<?php echo $this->project_data['id']; ?>" />
</p>
<?php endif; ?>

<?php if($this->task_data): ?>
<p>
	<label for="task_id">Task</label>
	<a href="<?php echo $this->url('tasks/view', array('task_id' => $this->task_data['id'])); ?>"><?php echo $this->task_data['name']; ?></a>
	<input type="hidden" name="task_id" value="<?php echo $this->task_data['id']; ?>" />
</p>
<?php endif; ?>

<p>
	<label for="description">Description</label>
	<?php $name = $form->get('description'); echo $this->formRow($name); ?>
</p>

<p>
	<input type="submit" class="submit" value="Submit" />
</p>
<?php echo $this->ConfirmPageUnload('#file_form')?>
<?php echo $this->form()->closeTag() ?>
<script type="text/javascript">

jQuery(document).ready(function($){

	$("input[type=file]").filestyle({ 
	     image: "<?php echo $this->StaticUrl(); ?>/images/browse.gif",
	     imageheight : 30,
	     imagewidth : 83,
	     width : 347
	 });	

	$("#file_form").validate({
		rules: {
			name: "required"
		},
		messages: {
			name: "Please enter a file name"
		}
	});

});
</script>