<table cellpadding="0" cellspacing="0" class="tablesorter" id="file_reviews">
	<thead>
		<tr>
			<th>Reviewer</th>
			<th>Review</th>			
			<th>Added</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<?php 
		$i = 0;
		foreach($this->reviews as $review)
		{
			$reviewer_data = array(
							'id' => $review['reviewer_id'], 
							'first_name' => $review['reviewer_first_name'], 
							'last_name' => $review['reviewer_last_name']
			);
		?>		
		<tr>
			<td><?php echo $this->MakeLink('user', $reviewer_data);?></td>
			<td><?php echo $this->Truncate($review['review']); ?></td>
			<td><?php echo $this->RelativeDate($review['created_date']); ?></td>
			<td>
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'files','action'=>'remove-review', 'id' => $review['id']), null, TRUE); ?>" title="Delete" rel="facebox"><?php echo $this->InteractIcon('cross', 'Delete');?></a>
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'files','action'=>'view-review', 'id' => $review['id']), null, TRUE); ?>" title="Preview" rel="facebox"><?php echo $this->InteractIcon('preview', 'Preview');?></a>
			</td>
		</tr>
		<?php 
			$i++;
		}
		?>
	</tbody>
</table>