<?php 
$form = $this->form;
$form->setAttribute('id', 'ip_form');
$form->setAttribute('action', $this->form_action);
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
<?php 
if($this->id > 0)
	echo '<input type="hidden" value="'.$this->id.'" name="id" />';
?>
	
		<p>
			<label for="ip">Ip</label>
			<?php $field = $form->get('ip'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="description">Description</label>
			<?php $field = $form->get('description'); echo $this->formRow($field); ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>			

<?php echo $this->ConfirmPageUnload('#ip_form')?>
<?php echo $this->form()->closeTag() ?>