<table cellpadding="0" cellspacing="0" class="<?php echo ($this->tableclass) ? $this->tableclass : 'tablesorter'; ?>" id="<?php echo ($this->tableid) ? $this->tableid : 'moji_ips'; ?>">
	<thead>
		<tr>
			<th>Ip Address</th>
			<th>Description</th>	
			<th>Created</th>
			<th>Modified</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<?php 
		$i = 0;
		foreach($this->ips as $ip)
		{
		?>
		<tr>
			<td>
			<a title="<?php echo $ip['ip_raw']; ?>" href="<?php echo $this->url('ips/view', array('ip_id'=> $ip['id'])); ?>" <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?>><?php echo $ip['ip_raw']; ?></a>
			</td>
			<td><?php echo $this->Truncate($ip['description']); ?></td>
			<td><?php echo $this->RelativeDate($ip['created_date']); ?></td>
			<td><?php echo $this->RelativeDate($ip['last_modified']); ?></td>
			
			<td>
			<?php if($this->CheckPermission('manage_projects')):?>
				<a href="<?php echo $this->url('ips/edit', array('ip_id'=> $ip['id']), null, TRUE); ?>" <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?> title="Edit"><?php echo $this->InteractIcon('pencil', 'Edit');?></a>
				<a href="<?php echo $this->url('ips/remove', array('ip_id'=> $ip['id']), null, TRUE); ?>" <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?> title="Delete"><?php echo $this->InteractIcon('cross', 'Delete');?></a>
			<?php endif; ?>
			</td>
		</tr>
		<?php 
		}
		?>
	</tbody>
</table>