<?php 
$form = $this->form;
$form->setAttribute('id', 'company_form');
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);

	if($this->id > 0)
		echo '<input type="hidden" value="'.$this->id.'" name="id" />';
?>	
<div id="form_tabs">
	<ul>

		<li><a href="#general">General</a></li>
		<li><a href="#address">Address</a></li>
		<li><a href="#phone">Phone</a></li>
	</ul>
	<div id="general">

		<p>
			<label for="name">Name</label>
			<?php $name = $form->get('name'); echo $this->formRow($name); ?>
		</p>

		<p>
			<label for="primary_url">Website</label>
			<?php $name = $form->get('primary_url'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="type">Type</label>
			<?php $name = $form->get('type'); echo $this->formRow($name); ?> 
		</p>
		
		<p style="display: none" id="client_language_block">
			<label for="client_language">Language</label>
			<?php $name = $form->get('client_language'); echo $this->formRow($name); ?>
		</p>
		
		<p style="display: none" id="currency_code_block">
			<label for="currency_code">Billing Currency</label>
			<?php $name = $form->get('currency_code'); echo $this->formRow($name); ?>
		</p>
		
		<p style="display: none" id="default_hourly_rate_block">
			<label for="default_hourly_rate">Default Hourly Rate</label>
			<?php $name = $form->get('default_hourly_rate'); echo $this->formRow($name); ?>
		</p>		
		
		<p>
			<label for="description">Description</label>
			<?php $name = $form->get('description'); echo $this->formRow($name); ?>
		</p>		
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>				
	</div>
	<div id="address">
		
		<p>
			<label for="address1">Address 1</label>
			<?php $name = $form->get('address1'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="address2">Address 2</label>
			<?php $name = $form->get('address2'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="city">City</label>
			<?php $name = $form->get('city'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="zip">Zip</label>
			<?php $name = $form->get('zip'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="state">State</label>
			<?php 
			$input = $form->getInputFilter();
			$name = $form->get('state'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>		
	
	</div>
	<div id="phone">
		<p>
			<label for="phone1">Phone</label>
			<?php $name = $form->get('phone1'); echo $this->formRow($name); ?>
		</p>
			
		<p>
			<label for="phone2">Phone 2</label>
			<?php $name = $form->get('phone2'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="fax">Fax</label>
			<?php $name = $form->get('fax'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>			
	</div>
</div>	
<?php echo $this->ConfirmPageUnload('#company_form')?>
<?php echo $this->form()->closeTag() ?>
<script type="text/javascript">
$.validator.setDefaults({
	//submitHandler: function() { alert("submitted!"); }
});

$().ready(function() {

	$("#company_form").validate({
		rules: {
			name: "required"
		},
		messages: {
			name: "Please enter a company name"
		}
	});

	var type = $("#type").val();
	if(type == 1)
	{
		$("#currency_code_block").show();
		$("#client_language_block").show();
		$("#default_hourly_rate_block").show();
	}

	$("#type").change(function(){
		//$("#assignment_comment").show();
		var def_type = '<?php echo ($this->company['type'] ? $this->company['type'] : 0); ?>';
		var new_type = $("#type").val();
		if(new_type == def_type || new_type == 1)
		{
			$("#currency_code_block").show();
			$("#client_language_block").show();
			$("#default_hourly_rate_block").show();
		}
		else
		{
			$("#currency_code_block").hide();
			$("#client_language_block").hide();
			$("#default_hourly_rate_block").hide();
		}
	});

});

</script>



