<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Ip Locker</div>
</div>
<p>
The Ip Locker allows Moji administrators the ability to "hide" their Moji account from unknown users. 
</p>

<h4>Actions</h4>

<p>
		<?php echo $this->InteractIcon('add', 'Add Ip Address');?> Add Ip Address
		<br /><?php echo $this->InteractIcon('pencil', 'Edit Ip Address');?> Edit Ip Address
		<br /><?php echo $this->InteractIcon('cross', 'Delete Ip Address');?> Remove Ip Address<br />
	
</p>