<?php $this->headTitle()->append( $this->_('account', 'app') ); ?>
<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('account', 'app'); ?></h1>
    </div>
      <div class="row">
        <div class="col-sm-3 col-md-3 sidebar">
            <?php echo $this->render('partials/_sidebar'); ?>
      </div>
      <div class="col-sm-9 col-md-9">
        <p>fdsa</p>
      </div>

    </div>
</div>    