<?php $this->headTitle()->append( $this->_('register', 'app') )->append( $this->_('account', 'app') ); ?>
<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('register', 'app'); ?></h1>
    </div>
    
    <?php
    $form = $this->form;
    $form->setAttribute('id', 'registerForm');
    $form->setAttribute('class', 'form-horizontal');
    $form->prepare();
    
    echo $this->form()->openTag($form);
    $csrf = $form->get('_x');
    echo $this->formRow($csrf);
    ?>
    
    
    <div class="form-group">
    	<label for="email" class="control-label col-xs-2"><?php echo $this->_('email', 'app'); ?></label>
    	<div class="col-xs-10">
            <?php
            $email = $form->get('email');
            echo $this->formRow($email);
            
            ?>
        </div>
    </div>
    
    <div class="form-group">
    	<label for="password" class="control-label col-xs-2"><?php echo $this->_('password', 'app'); ?></label>
    	<div class="col-xs-10">
        <?php
        $password = $form->get('password');
        echo $this->formRow($password);
        ?>
        </div>
    </div>
    
    <div class="form-group">
    	<label for="confirm_password" class="control-label col-xs-2"><?php echo $this->_('confirm_password', 'app'); ?></label>
    	<div class="col-xs-10">
        <?php
        $password = $form->get('confirm_password');
        echo $this->formRow($password);
        ?>
        </div>
    </div>
    
    <div class="form-group">
    	<div class="col-xs-offset-2 col-xs-10">
    		<button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo $this->_('register', 'app'); ?></button>
    	</div>
    </div>
    
    <?php echo $this->form()->closeTag() ?>
</div>