<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('verify_email', 'app'); ?></h1>
    </div>
    
    <?php 
    $form = $this->form;
    $form->setAttribute('id', 'verify_email_form');
    $form->setAttribute('action', $this->url('account/verify_email'));
    $form->prepare();
    echo $this->form()->openTag($form);
    $csrf = $form->get('_x');
    echo $this->formRow($csrf);
    ?>
    <p>
    <?php 
    $user_data = $this->UserInfo($this->GetIdentity());
    echo sprintf($this->_('verify_email_instructions', 'app'), $user_data['email']); ?></p>
        <input type="submit" class="btn btn-primary" value="<?php echo $this->_('verify_send_conf_email', 'app'); ?>" />
    <?php echo $this->form()->closeTag() ?>
</div>