<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Users</div>
</div>
<p>
This page lists all the users in the system
</p>

<?php if($this->CheckPermission('manage_users')):?>
<h4>Actions</h4>
<p>
	<?php echo $this->InteractIcon('add', 'Add User');?> Add User
	<br /><?php echo $this->InteractIcon('pencil', 'Edit');?> Edit User
	<br /><?php echo $this->InteractIcon('cross', 'Delete');?> Remove User<br />
</p>
<?php endif; ?>