<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<link rel="icon" href="<?php echo $this->StaticUrl(); ?>/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="<?php echo $this->StaticUrl(); ?>/favicon.ico" type="image/x-icon">
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<!-- MASTER STYLESHEET-->
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<link href="<?php echo $this->StaticUrl(); ?>/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>