<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<link rel="icon" href="<?php echo $this->StaticUrl(); ?>/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="<?php echo $this->StaticUrl(); ?>/favicon.ico" type="image/x-icon">
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<!-- MASTER STYLESHEET-->
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<link href="<?php echo $this->StaticUrl(); ?>/css/styles.css" rel="stylesheet" type="text/css" />

<!-- LOAD JQUERY -->
<script type="text/javascript" src="<?php echo $this->StaticUrl(); ?>/js/scripts.min.js"></script>

<link type="text/css" href="<?php echo $this->StaticUrl(); ?>/css/custom-theme/jquery-ui-1.7.2.custom.css" rel="stylesheet" />
<link href="<?php echo $this->StaticUrl(); ?>/css/datatables.css" rel="stylesheet" type="text/css" media="screen" />

<!-- LOAD FACEBOX -->
<link href="<?php echo $this->StaticUrl(); ?>/css/facebox.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" href="<?php echo $this->StaticUrl(); ?>/css/datepicker.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->StaticUrl(); ?>/css/calendar.css" type="text/css" />

<link href="<?php echo $this->StaticUrl(); ?>/css/jquery.moji-checkbox.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" href="<?php echo $this->StaticUrl(); ?>/css/chosen.css" type="text/css" />

<script src="<?php echo $this->StaticUrl(); ?>/js/scripts/jquery.countdown.min.js" type="text/javascript"></script>
<script src="<?php echo $this->StaticUrl(); ?>/js/scripts/chosen.jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->StaticUrl(); ?>/js/form.js"></script>
<script src="<?php echo $this->StaticUrl(); ?>/js/scripts.js" type="text/javascript"></script>
<!--[if IE 6]>
<script src="<?php echo $this->StaticUrl(); ?>/js/pngfix.js"></script>
<script>
    DD_belatedPNG.fix('.png_bg');
</script>        
<![endif]-->

<script type='text/javascript'>
(function (d, t) {
  var bh = d.createElement(t), s = d.getElementsByTagName(t)[0];
  bh.type = 'text/javascript';
  bh.src = '//www.bugherd.com/sidebarv2.js?apikey=cyte1tx1dagijmm51volpw';
  s.parentNode.insertBefore(bh, s);
  })(document, 'script');
</script>
</head>

<body>