<div id="primary_content">

	<?php if($this->title): ?>
		<h2><?php echo $this->escape($this->title); ?></h2>
	<?php endif; ?>
	<?php 
	if(count($this->messages) >= 1)
	{
		foreach($this->messages AS $message) 
		{		
			if(isset($message) && $message != ''){
				echo '<div class="success canhide png_bg">'.$message.'</div>';
			}
		}
	}
	?>	
	
	<?php 
	echo $this->error;
	if(count($this->errors) >= 1)
	{
		foreach($this->errors AS $error) 
		{		
			if(isset($error) && $error != ''){
				echo '<div class="fail canhide png_bg">'.$error.'</div>';
			}
		}
	}
	?>	
	
	<?php echo $this->layout()->content; ?>

	
</div>

<!--  START SIDEBAR -->
<div id="sidebar">
<?php echo $this->partial('layout/pm/sidebars/'.$this->sidebar)?>

</div><!--  end div #sidebar -->
<!--  END SIDEBAR -->