<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Allowed File Formats</div>
</div>
<p>
This is a list of all the file extensions allowed for upload through MojiTrac. It should be comma seperated and the entries should not
contain the dot. <br /><br />
For example:<br />
jpg,gif,png,txt,docx,doc,pdf,php,xls,xlsx,csv,psd,ppt,pptx,pot,potx,rar,zip,tar,gz,tgz,bz2,html,htm,avi,mov,fla,swf,asf,flv,sql,mp3


</p>