<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Time Formats</div>
</div>
<p>
Use the below codes to form your custom date format:</p>


<table width="500" class="doc_table">
  <tr>
    <th colspan="3" align="left">Day of Month</th>
  </tr>
  <tr>
    <td style="padding-left:5px;">d</td>
    <td>Numeric, with leading zeros</td>
    <td>01&ndash;31</td>
  </tr>
  <tr class="doctable_odd">
    <td style="padding-left:5px;">j</td>
    <td>Numeric, without leading zeros</td>
    <td>1&ndash;31</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">S</td>
    <td>English ordinal suffix, use after j</td>
    <td>st, nd, rd or th</td>
  </tr>
  <tr>
    <th colspan="3" align="left">Weekday</th>
  </tr>
  <tr>
    <td style="padding-left:5px;">l</td>
    <td>Full name &nbsp;(lowercase 'L')</td>
    <td>Sunday &ndash; Saturday</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">D</td>
    <td>Three letter name</td>
    <td>Mon &ndash; Sun</td>
  </tr>
  <tr>
    <th colspan="3" align="left">Month</th>
  </tr>
  <tr>
    <td style="padding-left:5px;">m</td>
    <td>Numeric, with leading zeros</td>
    <td>01&ndash;12</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">n</td>
    <td>Numeric, without leading zeros</td>
    <td>1&ndash;12</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">F</td>
    <td>Textual full</td>
    <td>January &ndash; December</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">M</td>
    <td>Textual three letters</td>
    <td>Jan - Dec</td>
  </tr>
  <tr>
    <th colspan="3" align="left">Year</th>
  </tr>
  <tr>
    <td style="padding-left:5px;">Y</td>
    <td>Numeric, 4 digits</td>
    <td>Eg., 1999, 2003</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">y</td>
    <td>Numeric, 2 digits</td>
    <td>Eg., 99, 03</td>
  </tr>
</table>