<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Time Formats</div>
</div>
<p>
Use the below codes to form your custom time format:</p>

<table width="100%" class="doc_table">
  <tr>
    <th colspan="3" align="left">Time</th>
  </tr>
  <tr>
    <td style="padding-left:5px;">a</td>
    <td>Lowercase</td>
    <td>am, pm</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">A</td>
    <td>Uppercase</td>
    <td>AM, PM</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">g</td>
    <td>Hour, 12-hour, without leading zeros</td>
    <td>1&ndash;12</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">h</td>
    <td>Hour, 12-hour, with leading zeros</td>
    <td>01&ndash;12</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">G</td>
    <td>Hour, 24-hour, without leading zeros</td>
    <td>0-23</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">H</td>
    <td>Hour, 24-hour, with leading zeros</td>
    <td>00-23</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">i</td>
    <td>Minutes, with leading zeros</td>
    <td>00-59</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">s</td>
    <td>Seconds, with leading zeros</td>
    <td>00-59</td>
  </tr>
  <tr>
    <td style="padding-left:5px;">T</td>
    <td>Timezone abbreviation</td>
    <td>Eg., EST, MDT ...</td>
  </tr>
</table>
