<div class="content_headers" style="padding-top:0px;">
	<div class="contact_header">Edit Contact</div>
</div>
<div class="back_link_content">
	<a href="<?php echo $this->url('contacts/view', array('contact_id'=>$this->contact_data['id'])); ?>" title="Back to <?php echo $this->contact_data['first_name'].' '.$this->contact_data['last_name'] ?>">
		Back to <?php echo $this->contact_data['first_name'].' '.$this->contact_data['last_name']; ?>	
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to '.$this->contact_data['first_name'].' '.$this->contact_data['last_name']);?></div>
</div>
<br clear="all" />
<?php 
$options = array('form' => $this->form, 'id' => $this->id);
echo $this->partial('pm/contacts/partials/form', $options); 
?>