<div class="attention png_bg">
Are you sure you want to remove "<?php echo $this->contact_data['first_name']?> <?php echo $this->contact_data['last_name']?>"? This can not be undone...
</div>


<?php 
$form = $this->form;
$form->setAttribute('id', 'remove_contact_form');
$form->setAttribute('action', $this->url('contacts/remove', array('contact_id' => $this->contact_data['id'])));
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
	<?php $field = $form->get('confirm'); echo $this->formRow($field); ?> <?php $field = $form->get('fail'); echo $this->formRow($field); ?>
<?php echo $this->form()->closeTag() ?>

<h2>Contact Details</h2>
<p>
<a href="<?php echo $this->url('contacts/view', array('contact_id'=>$this->contact_data['id'])); ?>"><?php echo $this->contact_data['first_name']?> <?php echo $this->contact_data['last_name']?></a> is attached to:
<br />
<?php if($this->file_count || $this->project_count || $this->task_count): ?>
	<?php echo $this->project_count; ?> Projects<br />
	<?php echo $this->task_count; ?> Tasks<br />
	<?php echo $this->file_count; ?> Files
	
<?php else: ?>
Nothing :)	
<?php endif; ?>
</p>