<div class="content_headers" style="padding-top:0px;">

	<div class="contact_header"><?php echo $this->contact['first_name']; ?> <?php echo $this->contact['last_name']; ?></div>
		
		<?php if($this->contact['email']): ?>
		<div class="actions">
			<a href="mailto:<?php echo $this->contact['email']; ?>" title="Contact">
				<?php echo $this->InteractIcon('email', 'Email Contact');?> 
				<div class="action_text">Email</div>
			</a>
		</div>
		<?php endif; ?>
		<?php if($this->contact['url']): ?>
		<div class="actions">
			<a href="<?php echo $this->contact['url']; ?>" target="_blank" title="Website"> 
				<?php echo $this->InteractIcon('www', 'Website');?>
				<div class="action_text">Website</div>
			</a>
		</div>
		<?php endif; ?>
		
		<?php if($this->CheckPermission('view_company_contacts')):?>
		<div class="actions">
			<a href="<?php echo $this->url('contacts/remove', array('module' => 'pm','controller'=>'contacts','action'=>'remove', 'id' => $this->id), null, TRUE); ?>" title="Delete" rel="facebox">
				<?php echo $this->InteractIcon('cross', 'Delete');?>
				<div class="action_text">Delete</div>
			</a>
		</div>		
		<div class="actions">
			<a href="<?php echo $this->url('contacts/edit', array('module' => 'pm','controller'=>'contacts','action'=>'edit', 'id' => $this->id), null, TRUE); ?>" title="Edit">
				<?php echo $this->InteractIcon('pencil', 'Edit');?>
				<div class="action_text">Edit</div>
			</a> 
		</div>
		<?php endif; ?>		
</div>

<div class="item_details">
    <div class="items" style="padding-left:10px;">
    	<p>
    		<?php if($this->contact['job_title']):?>
			<span class="bold">Title:</span> <?php echo $this->contact['job_title']; ?><br />
			<?php endif; ?>
			<span class="bold">Company:</span> <a href="<?php echo $this->url('companies/view', array('company_id' => $this->contact['company_id'])); ?>"><?php echo $this->contact['company_name']; ?></a><br />   
			<span class="bold">Last Modified:</span> <?php echo $this->RelativeDate($this->contact['last_modified']); ?><br />
			<span class="bold">Created Date:</span> <?php echo $this->RelativeDate($this->contact['created_date']); ?> 				
    	</p>
    </div> 

    <?php if($this->contact['state'] || $this->contact['address1'] || $this->contact['city'] || $this->contact['zip']):?>
    <div class="items" style="padding-left:10px;">
    	<p>
    		<?php if($this->contact['address1']):?>
				<span class="bold">Address 1:</span> <?php echo $this->contact['address1']; ?><br />
			<?php endif; ?> 
			<?php if($this->contact['address2']):?>
				<span class="bold">Address 2:</span> <?php echo $this->contact['address2']; ?><br />
			<?php endif; ?> 
			<?php if($this->contact['city']):?>
				<span class="bold">City:</span> <?php echo $this->contact['city']; ?><br />
			<?php endif; ?> 
			<?php if($this->contact['state']):?>
				<span class="bold">State:</span> <?php echo $this->contact['state']; ?><br />
			<?php endif; ?> 
			<?php if($this->contact['zip']):?>
				<span class="bold">Zip:</span> <?php echo $this->contact['zip']; ?>
			<?php endif; ?> 
    	</p>
    </div>
    <?php endif; ?>
    <?php if($this->contact['phone_home'] || $this->contact['phone2'] || $this->contact['fax'] || $this->contact['mobile']):?>
    <div class="items" style="padding-left:10px;">
    	<p>
			<?php if($this->contact['phone_home']):?>
				<span class="bold">Phone 1:</span> <?php echo $this->contact['phone1']; ?><br />
			<?php endif; ?>
			<?php if($this->contact['phone2']):?>
				<span class="bold">Phone 2:</span> <?php echo $this->contact['phone2']; ?><br />
			<?php endif; ?>
			<?php if($this->contact['fax']):?>
				<span class="bold">Fax:</span> <?php echo $this->contact['fax']; ?>  
			<?php endif; ?>  
			<?php if($this->contact['mobile']):?>
				<span class="bold">Mobile:</span> <?php echo $this->contact['mobile']; ?>  
			<?php endif; ?>  				
    	</p>
    </div>
    <?php endif; ?>  
    
    <?php if($this->contact['jabber'] || $this->contact['icq'] || $this->contact['msn'] || $this->contact['yahoo'] || $this->contact['aol'] || $this->contact['google_talk']):?>
    <div class="items" style="padding-left:10px;">
    	<p>
			<?php if($this->contact['jabber']):?>
				<span class="bold">Jabber:</span> <?php echo $this->contact['jabber']; ?><br />
			<?php endif; ?>
			<?php if($this->contact['icq']):?>
				<span class="bold">ICQ:</span> <?php echo $this->contact['icq']; ?><br />
			<?php endif; ?>
			<?php if($this->contact['msn']):?>
				<span class="bold">MSN:</span> <?php echo $this->contact['msn']; ?>  
			<?php endif; ?>  
			<?php if($this->contact['yahoo']):?>
				<span class="bold">Yahoo:</span> <?php echo $this->contact['yahoo']; ?>  
			<?php endif; ?>  
			<?php if($this->contact['aol']):?>
				<span class="bold">AOL:</span> <?php echo $this->contact['aol']; ?>  
			<?php endif; ?>  
			<?php if($this->contact['google_talk']):?>
				<span class="bold">Google Tralk:</span> <?php echo $this->contact['google_talk']; ?>  
			<?php endif; ?>			  										
    	</p>
    </div>
    <?php endif; ?>     
</div>

<br clear="all" />

<?php if($this->contact['description']): ?>
	<h2>Description:</h2>
	<p><?php echo nl2br($this->contact['description']); ?></p>
<?php endif; ?>
