Task: <a href="<?php echo $this->ServerUrl($this->url('tasks/view', array('task_id' => $task_data['id']))); ?>"><?php echo $task_data['name']; ?></a><br />

Expected Duration: <?php echo (!empty($task_data['duration']) ? $task_data['duration'] : 0);?> hours<br />
<?php 
$msg_html = '';
if($task_data['start_date'] && $task_data['start_date'] != '0000-00-00 00:00:00')
{
	$msg_html .= 'Start: '.$this->RelativeDate($task_data['start_date']).'<br />';
}
	
if($task_data['end_date'] && $task_data['end_date'] != '0000-00-00 00:00:00')
{
	$msg_html .= 'Due: '.$this->RelativeDate($task_data['end_date']).'<br />';
}

$msg_html .= 'Company: <a href="'.$this->ServerUrl($this->url('companies/view', array('company_id' => $project_data['company_id']))).'">'.$project_data['company_name'].'</a><br />';
$msg_html .= 'Project: <a href="'.$this->ServerUrl($this->url('projects/view', array('project_id' => $project_data['id']))).'">'.$task_data['project_name'].'</a><br />';
$msg_html .= 'Type: '.$this->TaskType($task_data['type']).'<br />';
$msg_html .= 'Priority: '.$this->TaskPriority($task_data['priority']).'<br />';
$msg_html .= 'Progress: '.$task_data['progress'].'%<br />';
$msg_html .= 'Status: '.$this->TaskStatus($task_data['status']).'<br /><br />';

$msg_html .= $this->FormatHtml($task_data['description']).'<br /><br />';
if(array_key_exists('assign_comment', $task_data) && $task_data['assign_comment'] != '')
{
	$msg_html .= 'Assignment Comment<br />'.$this->FormatHtml($task_data['assign_comment']).'<br />';
}
echo  $msg_html;