<ul class="nav nav-tabs">
    <li class="<?php echo ($this->active_tab == 'general' ? 'active"' : '') ; ?>"><a href="<?php echo $this->url('site_settings', array('site_id' => $this->layout()->site_data['id'], 'section' => 'general')); ?>"><?php echo $this->_('general_bp_settings_menu', 'sites'); ?></a></li>
    <li class="<?php echo ($this->active_tab == 'db' ? 'active"' : '') ; ?>"><a href="<?php echo $this->url('site_settings', array('site_id' => $this->layout()->site_data['id'], 'section' => 'db')); ?>"><?php echo $this->_('db_bp_settings_menu', 'sites'); ?></a></li>
    <li class="<?php echo ($this->active_tab == 'files' ? 'active"' : '') ; ?>"><a href="<?php echo $this->url('site_settings', array('site_id' => $this->layout()->site_data['id'], 'section' => 'files')); ?>"><?php echo $this->_('files_bp_settings_menu', 'sites'); ?></a></li>
    <li class="<?php echo ($this->active_tab == 'cron' ? 'active"' : '') ; ?>"><a href="<?php echo $this->url('site_settings', array('site_id' => $this->layout()->site_data['id'], 'section' => 'cron')); ?>"><?php echo $this->_('cron_bp_settings_menu', 'sites'); ?></a></li>
    <li class="<?php echo ($this->active_tab == 'storage_locations' ? 'active"' : '') ; ?>"><a href="<?php echo $this->url('site_settings', array('site_id' => $this->layout()->site_data['id'], 'section' => 'general')); ?>"><?php echo $this->_('storage_location_bp_settings_menu', 'sites'); ?></a></li>
    <li class="<?php echo ($this->active_tab == 'integrity_agent' ? 'active"' : '') ; ?>"><a href="<?php echo $this->url('site_settings', array('site_id' => $this->layout()->site_data['id'], 'section' => 'integrity_agent')); ?>"><?php echo $this->_('integrity_agent_bp_settings_menu', 'sites'); ?></a></li>
</ul>  

<br />