<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Task End Date</div>
</div>
<p>
Entering an End Date (along with a Start Date) is what really gets MojiTrac working. Tasks with End Dates will be added to the assigned users 
daily task reminder notification, show up on their personal task list and alert them when the deadline comes up and, 
eventually, passes. 

</p>