<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Task Status</div>
</div>
<p>
The Task Status is what enables or disables certain portions of the MojiTrac magic. Depending on what Status you choose Moji will do the following: 
<br /><br />

Not Defined: Task is disabled<br />
Proposed: Task is disabled though time can be logged<br />
In Planning: Task is disabled, time can be logged and shows on daily task reminder<br />
In Progress: Task is enabled, time can be logged, shows on assigned users todo list<br />
On Hold: Task is disabled<br />
Complete: Task is disabled. After 14 days the task status is set to Archived.<br />
Archived: Task is removed from system though still available within the view all screen<br />
</p>