<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Task Type</div>
</div>
<p>
<?php if($this->CheckPermission('manage_options')): ?>
	The Task Type is controlled through the 
	<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'options','action'=>'index'), null, TRUE); ?>" rel="facebox">admin</a> 
	where the options can be managed. For now, Task Types are simply a bucket used for categorizing the task though their use within 
	reporting is planned. 
<?php else: ?>
	The Task Type is a basic category for the Task. If you don't see an option you're looking for talk to the system administrator
	to add it. 
<?php endif; ?>
</p>