<div class="content_headers" style="padding-top:0px;">
	<div class="timetracker_header">Timetracker</div>
		<?php echo $this->ActionBlock('help', 'Help', $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'times', 'page' => 'main'), null, TRUE), 'facebox');?>	
	</div>
<?php
echo $this->Calendar($this->month, $this->year)
			->setData($this->calendar_data)
			->setDayRouteName('times/view-day')
			->setMonthRouteName('times/month')
			->getCalendarHtml(
					array(
							'showToday'=>TRUE,
							'showPrevMonthLink'=>TRUE,
							'showNextMonthLink'=>TRUE,
							'tableClass'=>"calendar",
							'selectBox'=>TRUE,
							'selectBoxName'=>"dateSelect",
							'selectBoxFormName'=>"selectMonthForm"
					)
			);
?>