<div class="content_headers" style="padding-top:0px;">
	<div class="timetracker_header">
	<?php if($this->company_data['name']): ?>
	Company Time Tracked For: <?php echo $this->company_data['name']; ?>
	<?php elseif($this->project_data['name']):?>
	Project Time Tracked For: <?php echo $this->project_data['name']; ?>	
	<?php elseif($this->task_data['name']):?>
	Task Time Tracked For: <?php echo $this->task_data['name']; ?>	
	<?php else: ?>
	Timetracker
	<?php endif; ?>
	</div>
		<div class="actions">
			<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'times','action'=>'view', 'export' => 'yes'), null, FALSE); ?>" title="Export Time">
				<?php echo $this->InteractIcon('save_disk', 'Export');?>
				<div class="action_text">Export</div>
			</a>
		</div>		
</div>


<?php 
$options = array('company' => $this->company_data, 'project' => $this->project_data, 'task' => $this->task_data, 'user' => $this->user_data);
echo $this->BackToLink($options); 
?>


<?php 
if($this->times): 
	if($this->CheckPermission('manage_time')): 
?>
<form action="<?php echo $this->url('pm', array('module' => 'pm','controller'=>'times','action'=>'update', 'id'=>$this->task['id']), null, TRUE); ?>" method="POST">
<?php endif; ?>
<?php 
	$options = array('times' => $this->times, 'enable_project' => 'yes', 'enable_task' => 'yes', 'enable_date' => 'yes');
	if($this->CheckPermission('manage_time'))
	{
		$options['enable_checkbox'] = 'yes';
	}
	
	echo $this->partial('pm/times/partials/times', $options); 
?>
<?php if($this->CheckPermission('manage_time')): ?>	
	<p>
		<?php if($this->company_data['name']): ?>
			<input type="hidden" value="<?php echo $this->company_data['id']?>" name="company" />
		<?php elseif($this->project_data['name']):?>
			<input type="hidden" value="<?php echo $this->project_data['id']?>" name="project" />	
		<?php elseif($this->task_data['name']):?>
			<input type="hidden" value="<?php echo $this->task_data['id']?>" name="task" />
		<?php elseif($this->user_data['id']):?>
			<input type="hidden" value="<?php echo $this->user_data['id']?>" name="user" />			
		<?php endif; ?>	
		<input type="hidden" name="status" value="<?php echo $this->bill_status; ?>" />
		<input type="hidden" name="update_type" value="bill_status" />
		
		<?php if($this->bill_status != 'unsent'): ?>
		<input name="mark_unpaid" type="submit" class="submit" value="Mark Unpaid" />
		<?php endif; ?>
		<?php if($this->bill_status != 'paid'): ?>
		<input name="mark_paid" type="submit" class="submit" value="Mark Paid" />
		<?php endif; ?>
		<?php if($this->bill_status != 'sent'): ?>
		<input name="mark_pending" type="submit" class="submit" value="Mark Pending" />
		<?php endif; ?>
		<?php if($this->bill_status != 'unbillable'): ?>
		<input name="mark_unbillable" type="submit" class="submit" value="Mark Unbillable" />
		<?php endif; ?>		
	</p> 	
	</form>
<?php endif; ?>	
<?php 
else: 
?>
<div class="information png_bg">There aren't any times added yet.</div>
<?php endif; ?>