<div class="content_headers" style="padding-top:0px;">
	<div class="timers_header">
	<?php if(!empty($this->timer_data['task_id'])): ?>
	Task Timer For: <?php echo $this->task['name']; ?>
	<?php elseif(isset($this->timer_data['project_id'])):?>
	Project Timer For: <?php echo $this->project['name']; ?>	
	<?php elseif(isset($this->timer_data['company_id'])):?>
	Company Timer For: <?php echo $this->company['name']; ?>	
	<?php else: ?>
	Timer
	<?php endif; ?>	
	</div>
		<div class="actions">
			<a href="<?php echo $this->url('timers/remove'); ?>" title="Delete">
				<?php echo $this->InteractIcon('cross', 'Delete');?>
				<div class="action_text">Delete</div>
			</a>
		</div>		
</div>

<?php 
$options = array(
	'form' => $this->form, 
	'timer_data' => $this->timer_data, 
	'project' => $this->project, 
	'task' => $this->task, 
	'company' => $this->company,
	'form_action' => $this->form_action
);
echo $this->partial('pm/timers/partials/form', $options); 
?>