<div class="content_headers" style="padding-top:0px;">
	<div class="file_header">Edit File</div>		
</div>
<?php 
$options = array('id' => $this->id, 'file' => $this->file_data, 'name' => $this->file_data['name'], 'action' => 'view');
echo $this->BackToLink($options); 

$options = array('form' => $this->form, 'id' => $this->id, 'form_action' => $this->form_action);
echo $this->partial('pm/files/partials/form.phtml', $options); 
?>