<div class="content_headers" style="padding-top:0px;">
	<div class="file_header">
	Files
	<?php if($this->company_data['id']): ?>
	For <?php echo $this->company_data['name']; ?>
	<?php endif; ?>
	<?php if($this->project_data['id']): ?>
	For <?php echo $this->project_data['name']; ?>
	<?php endif; ?>	
	<?php if($this->task_data['id']): ?>
	For <?php echo $this->task_data['name']; ?>
	<?php endif; ?>		
	</div>
		
		<div class="actions">
			<a href="<?php echo $this->url('files/add', array('type'=> $this->type,'id'=> $this->id)); ?>" rel="facebox" title="Add">
				<?php echo $this->InteractIcon('add', 'Add File');?>
				<div class="action_text">Add File</div>
			</a> 
		</div>			
</div>
<?php 
$options = array('company' => $this->company_data, 'project' => $this->project_data, 'task' => $this->task_data);
echo $this->BackToLink($options); 

if($this->file_data): 

	$options = array('files' => $this->file_data, 'enable_actions' => 'yes');
	echo $this->partial('pm/files/partials/files.phtml', $options);

else: ?>
<div class="information png_bg">There aren't any files uploaded yet. Want to <a href="<?php echo $this->url('files/add', array('type' => $type, 'id' => $id)); ?>">add</a> one?.</div>

<?php endif; ?>