<table class="table table-hover table-striped">
	<thead>
		<tr>
			<th>Ip Address</th>
			<th>Description</th>	
			<th>Created</th>
			<th>Modified</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<?php 
		$i = 0;
		foreach($this->ips as $ip)
		{
		?>
		<tr>
			<td>
			<a title="<?php echo $ip['ip_raw']; ?>" href="<?php echo $this->url('manage_ips/view', array('ip_id'=> $ip['id'])); ?>" <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?>><?php echo $ip['ip_raw']; ?></a>
			</td>
			<td><?php echo $this->Truncate($ip['description']); ?></td>
			<td><?php echo $this->FormatDate($ip['created_date']); ?></td>
			<td><?php echo $this->FormatDate($ip['last_modified']); ?></td>
			
			<td>
			<?php if($this->CheckPermission('manage_ips')):?>
				<a href="<?php echo $this->url('manage_ips/edit', array('ip_id'=> $ip['id']), null, TRUE); ?>" <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?> title="Edit"><?php echo $this->glyphicon('pencil');?></a>
				<a href="<?php echo $this->url('manage_ips/remove', array('ip_id'=> $ip['id']), null, TRUE); ?>" <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?> title="Delete"><?php echo $this->glyphicon('remove');?></a>
			<?php endif; ?>
			</td>
		</tr>
		<?php 
		}
		?>
	</tbody>
</table>