<div class="list-group">
    <a class="list-group-item <?php echo ($this->active_sidebar == 'manage_users' ? 'active' : ''); ?>" href="<?php echo $this->url('manage_users'); ?>"><?php echo $this->_('manage_users', 'cp'); ?></a>
    <a class="list-group-item <?php echo ($this->active_sidebar == 'system_settings' ? 'active' : ''); ?>" href="<?php echo $this->url('system_settings'); ?>"><?php echo $this->_('settings', 'cp'); ?></a>
</div>