<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Projects</div>
</div>
<p>
<?php if($this->CheckPermission('manage_projects')):?>
Below are all the projects in the system. 
<?php else: ?>
Below are all the projects you're assigned to. 
<?php endif; ?>

You can filter by the status type by using the submenu. From here you can:
<br /><br /></p>
<p>
	<?php if($this->CheckPermission('manage_projects')):?>
		<?php echo $this->InteractIcon('add', 'Add Project');?> Add new projects
		<br /><?php echo $this->InteractIcon('pencil', 'Edit');?> Edit projects
		<br /><?php echo $this->InteractIcon('cross', 'Delete');?> Remove projects<br />
	<?php endif; ?>
	<?php echo $this->InteractIcon('user', 'Project Team');?> View Project Team
	<br /><?php echo $this->InteractIcon('folder', 'Project Files');?> View Project Files
	
</p>