<?php 
$options = array();
switch($this->page)
{
	case 'view':
	case 'assignment-history':
	case 'team':
	case 'tasks':
	case 'notes':
	case 'files':
	case 'bookmarks':
	case 'times':
	case 'your-overdue-tasks':
	case 'your-tasks-due-tomorrow':
	case 'your-tasks-due-week':
	case 'your-upcoming-tasks':	
	case 'your-tasks-due-today':
	case 'assigned_to':
	case 'status':
	case 'start_date':
	case 'end_date':
	case 'progress':
	case 'duration':
	case 'type':
		$page = $this->page;
	break;	
	
	default:
		$page = 'main';
	break;
}

echo $this->partial('pm/docs/tasks/'.$page, $options); 
?>