<div class="content_headers" style="padding-top:0px;">
	<div class="import_header">Import Data</div>	
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'import', 'page' => 'main'), null, TRUE); ?>" rel="facebox" title="Add Project">
				<?php echo $this->InteractIcon('help', 'About Importing Data');?>
				<div class="action_text">Help</div>
			</a>
		</div>
</div>

<p>
<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'import','action'=>'harvest'), null, TRUE); ?>">Harvest</a><br />
</p>