<div class="content_headers" style="padding-top:0px;">

	<div class="reports_header">Task Reports</div>
	<?php echo $this->ActionBlock('help', 'Help', $this->url(array('module' => 'pm','controller' => 'docs','action'=>'companies', 'page' => 'main'), null, TRUE), 'facebox'); ?>
	<br clear="all" />		
</div>

<?php echo $this->FusionCharts('user_times', 'Column3D', 900, 400); ?>

<?php echo $this->FusionCharts('company_items', 'StackedBar2D', 900, 1200); ?>