<div class="content_headers" style="padding:0px;">
	<div class="user_header">Account Settings</div>	
</div>
<dl>
	<dt><a href="<?php echo $this->url('users/edit'); ?>">Modify Account Info</a></dt>
	<dd>Modify the information about your account.</dd>
	<dt><a href="<?php echo $this->url('account/password'); ?>">Change Password</a></dt>
	<dd>Change the password you use to login with.</dd>
	<dt><a href="<?php echo $this->url('account/prefs'); ?>">Preferences</a></dt>
	<dd>Update how MojiTRAC works just for you.</dd>	
</dl>