<div class="content_headers" style="padding-top:0px;">
	<div class="file_version_header">Viewing File Revision: <?php echo $this->Truncate($this->rev_data['file_name'], 30); ?></div>		
</div>
<?php if(!$this->preview_exists): ?>
<div class="fail png_bg">
Preview doesn't exist...
</div>

<?php
return;
endif;
?>
<img src="<?php echo $this->url('files/preview-revision', array('revision_id' => $this->rev_data['id'], 'view-type' => 'html')); ?>" />