<div class="content_headers" style="padding-top:0px;">
	<div class="file_version_header">Remove File Revision: <?php echo $this->Truncate($this->revision_data['file_name'], 30); ?></div>		
</div>
<?php 
$options = array('file_id' => $this->file_data['id'], 'controller' => 'files', 'name' => $this->file_data['name'], 'action' => 'view');
//echo $this->BackToLink($options);

if($this->total_file_revisions > 1): ?>
<div class="attention png_bg">
Are you sure you want to remove "<?php echo $this->Truncate($this->revision_data['file_name'], 30); ?>"? This can not be undone...
</div>

<p>
<?php 
$form = $this->form;
$form->setAttribute('id', 'file_form');
$form->setAttribute('action', $this->url('files/remove-revision', array('revision_id' => $this->revision_data['id'])));
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
	<?php $field = $form->get('confirm'); echo $this->formRow($field); ?> <?php $field = $form->get('fail'); echo $this->formRow($field); ?>
<?php echo $this->form()->closeTag() ?>
</p>
<?php else: ?>
<div class="fail png_bg">
You can't remove the only revision of a file. Delete the entire file entry instead.
</div>
<?php
endif; 
?>