Hello <?php echo $user_data['first_name']; ?>, <br /><br />

This is an automatic email to remind you of tasks that are assigned to you but not completed yet. Please login into the project management system and review your assigned tasks.<br />

<?php 

$lang['overdue'] = '<br />The following tasks are OVERDUE:<br />';
$lang['today'] = '<br />The following tasks are DUE TODAY:<br />';
$lang['tomorrow'] = '<br />The following tasks are DUE TOMORROW:<br />';
$lang['within_week'] = '<br />The following tasks are WITHIN A WEEK:<br />';
$lang['upcoming'] = '<br />The following tasks are in the coming week(s):<br />';
foreach($lang AS $type => $str)
{
	if(array_key_exists($type, $tasks) && is_array($tasks[$type]))
	{
		if(count($tasks[$type]) >= 1)
		{
			foreach($tasks[$type] AS $task)
			{
				$lang[$type] .= "<a href='"."".$this->AccountUrl($task['account_id'], $this->url('tasks/view', array('task_id' => $task['id'])))."'>".$task['name']."</a> (".$this->RelativeDate($task['end_date']).")<br>";
			}
			continue;
		}
	}
	unset($lang[$type]);
}

echo (is_array($lang) ? implode('', $lang) : FALSE);
?>

<br /><br /><?php echo $this->_('sent_by_moji', 'pm'); ?>
<br />Want to stop these emails? You can manage your notifcations within <a href="<?php echo $this->AccountUrl($task['account_id'], $this->url('account/prefs')); ?>">MojiTrac</a> too.