

<h2><?php echo $this->_('login_welcome_message', 'app'); ?></h2>		
<?php 
$form = $this->form;
$form->setAttribute('id', 'sumbitForm');
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

if(is_array($this->messages) && count($this->messages) >= 1)
{
	foreach($this->messages AS $message) 
	{
		echo '<div class="success large png_bg">'.$message.'</div>';
	}
} else {
	
	echo '<div class="information large png_bg">'.$this->_('login_instructions', 'app').'</div> ';
}

echo $this->form()->openTag($form); 
$csrf = $form->get('_x');
echo $this->formRow($csrf); 
?>


<div class="form-group">
    <label for="email" class="control-label col-xs-2"><?php echo $this->_('email', 'app'); ?></label>
    <div class="col-xs-10">
        <?php 
        $email = $form->get('email');
        echo $this->formRow($email); 
        ?>
    </div>
</div>

<div class="form-group">
    <label for="password" class="control-label col-xs-2"><?php echo $this->_('password', 'app'); ?></label>
    <div class="col-xs-10">
    <?php 
    $password = $form->get('password');
    echo $this->formRow($password); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-xs-offset-2 col-xs-10">
<button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo $this->_('sign_in', 'app'); ?></button>

<br />
<a href="<?php echo $this->url('forgot-password'); ?>"><?php echo $this->_('forgot_password', 'app'); ?></a> | 
<a href="<?php echo $this->url('account/register'); ?>"><?php echo $this->_('register', 'app'); ?></a>
</div>
</div>
		
	<?php echo $this->form()->closeTag() ?>
	
<script type="text/javascript">
$.validator.setDefaults({
	//submitHandler: function() { alert("submitted!"); }
});

$().ready(function() {

	$("#email").focus();
	$("#sumbitForm").validate({
		rules: {
			email: "required",
			password: "required"
		},
		messages: {
			email: "<?php echo $this->_('js_email_validation_message', 'app'); ?>",
			password: "<?php echo $this->_('js_password_validation_message', 'app'); ?>"
		}
	});

});

</script>	