<h1><?php echo $this->_('login_welcome_message', 'app'); ?></h1>		
<?php 
$form = $this->form;
$form->setAttribute('id', 'sumbitForm');
$form->prepare();

if(is_array($this->messages) && count($this->messages) >= 1)
{
	foreach($this->messages AS $message) 
	{
		echo '<div class="success large png_bg">'.$message.'</div>';
	}
} else {
	
	echo '<div class="information large png_bg">'.$this->_('login_instructions', 'app').'</div> ';
}

echo $this->form()->openTag($form); 
$csrf = $form->get('_x');
echo $this->formRow($csrf); 
?>
<p><label><?php echo $this->_('email', 'app'); ?></label>
<?php 
$email = $form->get('email');
echo $this->formRow($email); ?>
</p>

<p><label><?php echo $this->_('password', 'app'); ?></label>
<?php 
$password = $form->get('password');
echo $this->formRow($password); ?>
</p>

<p>
<input type="submit" name="Submit" id="button" value="Login"  class="button"/>
<input type="reset" name="reset" id="reset" value="Reset" class="button" />

<br />
<a href="<?php echo $this->url('forgot-password'); ?>"><?php echo $this->_('forgot_password', 'app'); ?></a>
</p>
		
	<?php echo $this->form()->closeTag() ?>
	
<script type="text/javascript">
$.validator.setDefaults({
	//submitHandler: function() { alert("submitted!"); }
});

$().ready(function() {

	$("#email").focus();
	$("#sumbitForm").validate({
		rules: {
			email: "required",
			password: "required"
		},
		messages: {
			email: "<?php echo $this->_('js_email_validation_message', 'app'); ?>",
			password: "<?php echo $this->_('js_password_validation_message', 'app'); ?>"
		}
	});

});

</script>	