<table cellpadding="0" cellspacing="0" class="<?php echo ($this->tableclass) ? $this->tableclass : 'tablesorter'; ?>" id="<?php echo ($this->tableid) ? $this->tableid : 'moji_roles'; ?>">
	<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>Added</th>
			<th>Last Modified</th>
			<?php if($this->enable_actions && $this->CheckPermission('manage_roles')):?>
			<th>Actions</th>
			<?php endif; ?>
		</tr>
	</thead>

	<tbody>
		<?php 
		$i = 0;
		foreach($this->roles as $role)
		{
 
			$role_link = array(
							'id' => $role['id'], 
							'name' => $role['name']
			);		
		?>
		<tr>
			<td><?php echo $this->MakeLink('role', $role_link);?></td>
			<td><?php echo ($role['description'] != '' ? $role['description'] : 'N/A'); ?></td>
			<td><?php echo $this->RelativeDate($role['created_date']); ?></td>
			<td><?php echo $this->RelativeDate($role['last_modified']); ?></td>
			<?php if($this->enable_actions && $this->CheckPermission('manage_roles')):?>
			<td>
			<a href="<?php echo $this->url('roles/edit', array('role_id'=>$role['id']), null, TRUE); ?>" title="Edit"><?php echo $this->InteractIcon('pencil', 'Edit');?></a>
			<a href="<?php echo $this->url('roles/remove', array('role_id'=>$role['id']), null, TRUE); ?>" title="Delete" <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?>><?php echo $this->InteractIcon('cross', 'Delete');?></a>
			</td>
			<?php endif; ?>
		</tr>
		<?php 
		}
		?>
	</tbody>
</table>