<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Company View</div>
</div>
<p>
This page lists all the details on a given company. A company in MojiTrac can be defined one of 2 ways depending on what the type of 
company it is:
<br /><br />
1. A common address book which can contain various notes, bookmarks, contacts and files; this is what occurs for 
Vendor, Supplier, Consultant, Government
<br /><br />
2. A client or internal company are both special type of company that opens up the project manager, task manager and time tracker 
modules; this is what occurs for Clients, Internal and Not Applicable. 

</p>