
<form action="<?php echo $this->escape($this->form->getAction()); ?>" 
method="<?php echo $this->escape($this->form->getMethod()) ?>"> 
	
		<p>
			<label for="reset_phrase">Please type the below phrase exactly to initiate the system reset:<br /><br />
			<?php echo $this->phrase; ?></label>
			<?php echo $this->form->reset_phrase; ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>			
</form>	