<?php 
$form = $this->form;
$form->setAttribute('id', 'form_settings');
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
<div id="form_tabs">
	<ul>
		<li><a href="#general">General</a></li>
		<li><a href="#companies">Companies</a></li>
		<li><a href="#projects">Projects</a></li>
		<li><a href="#tasks">Tasks</a></li>
	</ul>
	<div id="general">
		<p>
			<label for="master_company">Master Company</label>
			<?php $field = $form->get('master_company'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="enable_ip"><?php $field = $form->get('enable_ip'); echo $this->formRow($field); ?> Enable Ip Locker</label>
		</p>
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>
	</div>	
	<div id="companies">
		<p>
			<label for="default_company_type">Default Company Type</label>
			<?php $field = $form->get('default_company_type'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="default_company_client_language">Default Company Language</label>
			<?php $field = $form->get('default_company_client_language'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="default_company_currency_code">Default Company Currency Code</label>
			<?php $field = $form->get('default_company_currency_code'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="default_company_hourly_rate">Default Company Hourly Rate</label>
			<?php $field = $form->get('default_company_hourly_rate'); echo $this->formRow($field); ?>
		</p>
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>
	</div>	
	<div id="projects">
		<p>
			<label for="default_project_type">Default Project Type</label>
			<?php $field = $form->get('default_project_type'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="default_project_priority">Default Project Priority</label>
			<?php $field = $form->get('default_project_priority'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="default_project_status">Default Project Status</label>
			<?php $field = $form->get('default_project_status'); echo $this->formRow($field); ?>
		</p>
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>
	</div>	
	<div id="tasks">
		<p>
			<label for="default_task_type">Default Task Type</label>
			<?php $field = $form->get('default_task_type'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="default_task_priority">Default Task Priority</label>
			<?php $field = $form->get('default_task_priority'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="default_task_status">Default Task Status</label>
			<?php $field = $form->get('default_task_status'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="task_auto_archive_days">Task Auto Archive Days</label>
			<?php $field = $form->get('task_auto_archive_days'); echo $this->formRow($field); ?>
		</p>
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>
	</div>	
</div>	
<?php echo $this->ConfirmPageUnload('#form_settings')?>
<?php echo $this->form()->closeTag() ?>