<div class="content_headers" style="padding-top:0px;">
	<div class="calendar_header">Project Activity For <?php echo $this->RelativeDate(date('Y-m-d', mktime(0, 0, 0, $this->month, $this->day, $this->year))); ?></div>
</div>
<?php 
$next_day = date('j', mktime(0, 0, 0, $this->month, $this->day+1, $this->year));
$next_year = date('Y', mktime(0, 0, 0, $this->month, $this->day+1, $this->year));
$next_month = date('n', mktime(0, 0, 0, $this->month, $this->day+1, $this->year));
$display_next_date = date('Y-m-d', mktime(0, 0, 0, $this->month, $this->day+1, $this->year));

$prev_day = date('j', mktime(0, 0, 0, $this->month, $this->day-1, $this->year));
$prev_year = date('Y', mktime(0, 0, 0, $this->month, $this->day-1, $this->year));
$prev_month = date('n', mktime(0, 0, 0, $this->month, $this->day-1, $this->year));
$display_prev_date = date('Y-m-d', mktime(0, 0, 0, $this->month, $this->day-1, $this->year));
?>
<div >
	<div class="left">
		<div class="back_link_content">
			<a href="<?php echo $this->url('calendar/view-day', array('day'=>$prev_day, 'month' => $prev_month, 'year' => $prev_year), null, TRUE); ?>" title="Back to <?php echo $this->user_data['first_name'].' '.$this->user_data['last_name']; ?>">
				<?php echo $this->RelativeDate($display_prev_date); ?>	
			</a><div><?php echo $this->InteractIcon('left-arrow', $this->RelativeDate($display_prev_date, false));?></div>
		</div>
	</div>
	<div class="right">
		<div class="back_link_content">
			<a href="<?php echo $this->url('calendar/view-day', array('day' => $next_day,'month'=>$next_month,'year'=>$next_year)); ?>">
				<?php echo $this->RelativeDate($display_next_date); ?> 
			</a><div style="float:right; padding-left:5px;"><?php echo $this->InteractIcon('right-arrow', $this->RelativeDate($display_next_date, false));?></div>
		</div>	
	</div>
</div>

<?php 
if($this->project_data):
	$options = array('projects' => $this->project_data, 'enable_company' => 'yes');
	echo $this->partial('pm/projects/partials/projects', $options);

else: ?>
<br clear="all" />
<div class="information png_bg">There aren't any projects for this date.</div>

<?php 
endif; 
?>
<div class="content_headers" style="padding-top:0px;">
	<div class="task_header">Tasks</div>
</div>
<?php 
if($this->task_data):
	$options = array('tasks' => $this->task_data, 'enable_project' => 'yes', 'enable_assigned' => 'yes', 'enable_completion' => 'yes', 'enable_due' => 'yes', 'enable_start' => 'yes');
	echo $this->partial('pm/tasks/partials/tasks', $options);

else: ?>
<br clear="all" />
<div class="information png_bg">There aren't any tasks for this date.</div>

<?php 
endif; 
?>