<?php 
$form = $this->form;
$form->setAttribute('id', 'password_form');
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);

?>
	<p>
		<label for="old_password">Current Password</label>
		<?php $field = $form->get('old_password'); echo $this->formRow($field); ?>
	</p>				
	
	<p>
		<label for="new_password">New Password</label>
		<?php $field = $form->get('new_password'); echo $this->formRow($field); ?>
	</p>			
	
	<p>
		<label for="confirm_password">Confirm Password</label>
		<?php $field = $form->get('confirm_password'); echo $this->formRow($field); ?>
	</p>
			
	
	<p>
		<input type="submit" class="submit" value="Submit" />
	</p>				

<?php echo $this->ConfirmPageUnload('#password_form')?>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
jQuery(document).ready(function($){
	$("#password_form").validate({
		rules: {
			old_password: {
				required: true
			},
			new_password: {
				required: true,
				minlength: 5
			},
			confirm_password: {
				required: true,
				equalTo: "#new_password",
				minlength: 5
			}
		},
		messages: {
			old_password: {
				required: "Please enter your old password",
			},			
			new_password: {
				required: "Please enter a new password",
				minlength: "Your password must be at least 5 characters long"
			},
			confirm_password: {
				required: "Please confirm your new password",
				equalTo: "Please enter the same password as above",
				minlength: "Your password must be at least 5 characters long"
			}
					
		}
	});	
});
</script>