<table cellpadding="0" cellspacing="0"
	class="<?php echo ($this->tableclass) ? $this->tableclass : 'tablesorter'; ?>"
	id="<?php echo ($this->tableid) ? $this->tableid : 'moji_users'; ?>">
	<thead>
		<tr>
			<?php if($this->project_team):?>
			<th></th>
			<?php endif; ?>
			<th></th>
			<th>Name</th>
			<th>Email</th>
			<th>Phone</th>
			<?php if($this->user_status):?>
				<th>Status</th>
			<?php endif; ?>
			<th>Added</th>
			<th>Last Modified</th>
			<?php if($this->enable_actions):?>
			<th class="{sorter: false}">Actions</th>
			<?php endif; ?>
		</tr>
	</thead>

	<tbody>
		<?php
$i = 0;
foreach ($this->users as $user) {
    ?>
		<tr>
			<?php if($this->project_team): //a little janky having this in the users template; considering changing. ?>
			<td><input type="checkbox"
				name="proj_member[<?php echo $user['id']?>]"
				<?php echo (is_array($this->proj_team) && in_array($user['id'], $this->proj_team) ? 'checked="checked"' : ''); ?> /></td>
			<?php endif; ?>
			<td>
			<?php
    $gravatar_settings = array(
        'img_size' => 25,
        'default_img' => \Zend\View\Helper\Gravatar::DEFAULT_MM,
        'rating' => \Zend\View\Helper\Gravatar::RATING_G,
        'secure' => null
    );
    echo $this->gravatar($user['email'], $gravatar_settings)->getImgTag();
    ?>	
			</td>
			<td><a
				title="<?php echo $user['first_name']; ?> <?php echo $user['last_name']; ?>"
				href="<?php echo $this->url('users/view', array('user_id'=>$user['id'])); ?>"><?php echo $user['first_name']; ?> <?php echo $user['last_name']; ?></a></td>
			<td><a title="<?php echo $user['email']; ?>"
				href="mailto:<?php echo $user['email']; ?>"><?php echo $user['email']; ?></a></td>
			<td><?php echo ($user['phone_home'] != '' ? $user['phone_home'] : 'N/A'); ?></td>
			<?php if($this->user_status):?>
				<td><?php echo ($user['user_status'] == 'd' ? 'Active' : 'Inactive'); ?></td>
			<?php endif; ?>
			<td><?php echo $this->RelativeDate($user['created_date']); ?></td>
			<td><?php echo $this->RelativeDate($user['last_modified']); ?></td>
			<?php if($this->enable_actions):?>
			<td>
			<?php if($this->getIdentity() == $user['id']): ?>
				<a
				href="<?php echo $this->url('users/edit', array('user_id'=>$user['id'])); ?>"
				title="Edit"><?php echo $this->InteractIcon('pencil', 'Edit User');?></a> 
			<?php endif; ?>
			<?php if($this->getIdentity() != $user['id']): ?>
				<a
				href="<?php echo $this->url('users/remove', array('user_id'=>$user['id'])); ?>"
				title="Delete" rel="facebox"><?php echo $this->InteractIcon('cross', 'Remove User');?></a>
				<a
				href="<?php echo $this->url('users/roles', array('user_id'=>$user['id'])); ?>"
				title="Roles" rel="facebox"><?php echo $this->InteractIcon('user_roles', 'User Roles');?></a> 
			<?php endif; ?>
			</td>
			<?php endif; ?>
		</tr>
		<?php 
		}
		?>
	</tbody>
</table>