<div class="content_headers" style="padding-top:0px;">
	<div class="note_header">Edit Note</div>
</div>
<?php 
$options = array('id' => $this->id, 'controller' => 'notes', 'name' => 'Note', 'action' => 'view');
//echo $this->BackToLink($options); 
?>

<?php 
$options = array('form' => $this->form, 'company' => $this->company, 'project' => $this->project, 'task' => $this->task, 'form_action' => $this->form_action, 'id' => $this->id);
echo $this->partial('pm/notes/partials/form', $options); 
?>