<div class="content_headers" style="padding-top:0px;">

	<div class="note_header">
	<?php if($this->company): ?>
		Company Notes For: <?php echo $this->company['name']; ?>
	<?php elseif($this->project): ?>
		Project Notes For: <?php echo $this->project['name']; ?>
	<?php elseif($this->task): ?>
		Task Notes For: <?php echo $this->task['name']; ?>		
	<?php else: ?>
		Notes
	<?php endif; ?>
	</div>

		<?php if($this->CheckPermission('view_company_contacts')):?>	
		<div class="actions">
			<a href="<?php echo $this->url('notes/add', array('type'=> $this->type,'id'=> $this->id)); ?>" title="Add">
				<?php echo $this->InteractIcon('add', 'Add Note');?>
				<div class="action_text">Add Note</div>
			</a> 
		</div>
		<?php endif; ?>	
</div>
	
<?php 
$options = array('company' => $this->company, 'project' => $this->project, 'task' => $this->task);
echo $this->BackToLink($options); 

if($this->notes): 

	$options = array('notes' => $this->notes, 'enable_actions' => 'yes', 'facebox' => 'yes');
	echo $this->partial('pm/notes/partials/notes', $options);

else: ?>

<div class="information png_bg">There aren't notes added yet. Want to <a href="<?php echo $this->url('pm', array('module' => 'pm','controller'=>'notes','action'=>'add'), null, TRUE); ?>">add</a> one?.</div>

<?php endif; ?>