<?php $this->headTitle()->append( $this->_('dashboard', 'sites') )->append( $site_data['site_name'] ); ?>
<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('dashboard', 'sites'); ?> <small><?php echo $site_data['site_name']; ?></small></h1>
    </div>
      <div class="row">
        <div class="col-sm-3 col-md-3 sidebar">
            <?php echo $this->render('sites/global/_sidebar', array('site_data' => $site_data)); ?>
      </div>
      <div class="col-sm-9 col-md-9">
      
      <?php echo $this->render('sites/global/_errors', array('site_data' => $site_data)); ?>
      <?php echo $this->render('partials/_tabs', array('active_tab' => 'database_backups', 'site_data' => $site_data)); ?>
       
      
        <div class="panel">
        	<table class="table"  width="100%"  border="0" cellpadding="0" cellspacing="0">
        	<thead>
        		<tr class="even">
        			<th nowrap><?php echo $this->_('total_backups', 'sites')?></th>
        			<th style="width:65%"><?php echo $this->_('total_space_used', 'sites'); ?></th>
        			<th nowrap><div style="float:right"><?php echo $this->_('last_backup_taken', 'sites'); ?></div></th>
        			<th nowrap><div style="float:right"><?php echo $this->_('first_backup_taken', 'sites'); ?></div></th>
        		</tr>
        	</thead>
        	<tbody>
        		<tr class="odd">
        			<td><?php echo $backup_meta['database']['total_backups']; ?></td>
        			<td><?php echo $backup_meta['database']['total_space_used']; ?></td>
        			<td><div style="float:right"><?php echo ($backup_meta['database']['newest_backup_taken'] != '' ? $this->m62DateTime($backup_meta['database']['newest_backup_taken']) : $this->_('na', 'sites')); ?></div></td>
        			<td><div style="float:right"><?php echo ($backup_meta['database']['oldest_backup_taken'] != '' ? $this->m62DateTime($backup_meta['database']['oldest_backup_taken']) : $this->_('na', 'sites')); ?></div></td>
        		</tr>
        	</tbody>
        	</table>
        </div>   
        
        
        
        <div class=" panel">
        
        	<?php 
        		if(count($backups) > 0):
        			$options = array('enable_type' => 'no', 'enable_editable_note' => 'yes', 'enable_actions' => 'yes', 'enable_delete' => 'yes', 'backups' => $backups);
                    echo $this->render('partials/_backup_table', $options);
        			//include '_includes/_backup_table.php';
        	?>
        	<?php else: ?>
        		<div class="no_backup_found"><?php echo $this->_('no_backups_exist', 'sites')?> <a href="<?php echo $this->url('backup', array('site_id' => $site_data['id'], 'type' => 'database')); ?>"><?php echo $this->_('would_you_like_to_backup_database_now', 'sites')?></a></div>
        	<?php endif; ?>
        
        </div>      
      
      
      
      </div>

    </div>
</div>    