<?php $this->headTitle()->append( $this->_('add_site', 'sites') )->append( $this->_('sites', 'sites') ); ?>
<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('add_site', 'sites'); ?> <small><?php echo $this->_('sites', 'sites'); ?></small></h1>
    </div>
      <div class="row">
        <div class="col-sm-3 col-md-3 sidebar">
            <?php echo $this->render('sites/global/_sidebar'); ?>
      </div>
      <div class="col-sm-9 col-md-9">fdsa     
      
      
      </div>

    </div>
</div>    