<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8">
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle('MojiTrac'); ?>
<?php //echo $this->headLink()->prependStylesheet('/css/site.css'); ?>
<link rel="icon" href="<?php echo $this->StaticUrl(); ?>/favicon.ico"
		type="image/x-icon">
		<link rel="shortcut icon"
			href="<?php echo $this->StaticUrl(); ?>/favicon.ico"
			type="image/x-icon">
			<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
			<link href="<?php echo $this->StaticUrl(); ?>/css/bootstrap.min.css"
				rel="stylesheet" type="text/css" />

			<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
			<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
			<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

			<style type="text/css">
body {
	padding-top: 70px;
}
</style>

</head>

<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
				data-toggle="collapse" data-target="#navbar" aria-expanded="false"
				aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php echo $this->url('home');?>">mithra62</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li
					class="<?php echo ($this->active_nav == 'home' ? 'active' : ''); ?>"><a
					href="<?php echo $this->url('home');?>">Home</a></li>
				<li
					class="<?php echo ($this->active_nav == 'about' ? 'active' : ''); ?>"><a
					href="<?php echo $this->url('about'); ?>">About</a></li>
            <?php if( $this->GetIdentity() ): ?>
                <li
					class="<?php echo ($this->active_nav == 'account' ? 'active' : ''); ?>"><a
					href="<?php echo $this->url('account'); ?>">Account</a></li>
			<?php if( $this->CheckPermission('admin_access') ): ?>	
				<li
					class="<?php echo ($this->active_nav == 'admin' ? 'active' : ''); ?>"><a
					href="<?php echo $this->url('about'); ?>">Admin</a></li>
		    <?php endif; ?>
				<li><a href="<?php echo $this->url('account/logout');?>">Logout</a></li>
            <?php else: ?>
                <li
					class="<?php echo ($this->active_nav == 'login' ? 'active' : ''); ?>"><a
					href="<?php echo $this->url('login');?>">Login</a></li>
            <?php endif; ?>
            <li><a href="<?php echo $this->url('about'); ?>">Contact</a></li>
			</ul>
		</div>
		<!--/.nav-collapse -->
	</div>
	</nav>

	<div class="container">
    
        <?php
        $flash = $this->flashMessenger();
        $flash->setMessageOpenFormat('<div%s>
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                 &times;
             </button>
             <ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');
        
        echo $flash->render('error', array(
            'alert',
            'alert-dismissible',
            'alert-danger'
        ));
        echo $flash->render('info', array(
            'alert',
            'alert-dismissible',
            'alert-info'
        ));
        echo $flash->render('default', array(
            'alert',
            'alert-dismissible',
            'alert-warning'
        ));
        echo $flash->render('success', array(
            'alert',
            'alert-dismissible',
            'alert-success'
        ));
        echo $this->layout()->content;
        ?>
    </div>

	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="<?php echo $this->StaticUrl(); ?>/js/jquery.min.js"><\/script>')</script>
	<script src="<?php echo $this->StaticUrl(); ?>/js/bootstrap.min.js"></script>
	<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
	<script
		src="<?php echo $this->StaticUrl(); ?>/js/ie10-viewport-bug-workaround.js"></script>
	<script src="<?php echo $this->StaticUrl(); ?>/js/jquery.validate.js"></script>
	<script src="<?php echo $this->StaticUrl(); ?>/js/form.js"></script>

</body>
</html>
