<?php $this->headTitle()->append( $this->_('add_site', 'sites') )->append( $this->_('sites', 'sites') ); ?>
<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('add_site', 'sites'); ?> <small><?php echo $this->_('sites', 'sites'); ?></small></h1>
    </div>
      <div class="row">
        <div class="col-sm-3 col-md-3 sidebar">
            <?php echo $this->render('sites/global/_sidebar'); ?>
      </div>
      <div class="col-sm-9 col-md-9">


        <?php
        $form = $this->form;
        $form->setAttribute('id', 'add_site_form');
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();
        
        echo $this->form()->openTag($form);
        $csrf = $form->get('_x');
        echo $this->formRow($csrf);
        ?>     
        
        <div class="form-group">
        	<label for="new_email" class="control-label col-xs-3"><?php echo $this->_('api_endpoint_url', 'sites'); ?></label>
        	<div class="col-xs-9">
                <?php
                $field = $form->get('api_endpoint_url');
                echo $this->formRow($field);
                
                ?>
            </div>
        </div>
    
        <div class="form-group">
        	<label for="api_key" class="control-label col-xs-3"><?php echo $this->_('api_key', 'sites'); ?></label>
        	<div class="col-xs-9">
            <?php
            $field = $form->get('api_key');
            echo $this->formRow($field);
            ?>
            </div>
        </div>
        
        <div class="form-group">
        	<label for="api_secret" class="control-label col-xs-3"><?php echo $this->_('api_secret', 'sites'); ?></label>
        	<div class="col-xs-9">
            <?php
            $field = $form->get('api_secret');
            echo $this->formRow($field);
            ?>
            </div>
        </div>
        
        <div class="form-group">
        	<div class="col-xs-offset-2 col-xs-10">
        		<button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo $this->_('add_site', 'sites'); ?></button>
        	</div>
        </div>      
      <?php echo $this->form()->closeTag() ?>    
      
      </div>

    </div>
</div>    