<?php $this->headTitle()->append( $this->_('delete_user', 'app') )->append( $this->_('admin', 'app') ); ?>
<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('remove_site', 'sites'); ?> <small><?php echo $this->_('sites', 'sites'); ?></small></h1>
    </div>
      <div class="row">
        <div class="col-sm-3 col-md-3 sidebar">
            <?php echo $this->render('sites/global/_sidebar'); ?>
      </div>
      <div class="col-sm-9 col-md-9">
      <h2><?php echo $this->_('remove_site', 'sites'); ?></h2>
        <a class="btn btn-primary  pull-right" href="<?php echo $this->url('sites/add'); ?>" role="button"><?php echo $this->glyphicon('plus'); ?> <?php echo $this->_('add_site', 'sites'); ?></a>
      
            <?php 
            $form = $this->form;
            $form->setAttribute('id', 'site_form');
            $form->prepare();
            echo $this->form()->openTag($form);
            $csrf = $form->get('_x');
            echo $this->formRow($csrf);
            
            $url = $this->url('sites/view', array('site_id' => $site_data['id']));
            echo sprintf($this->_('remove_user_question', 'app'), $site_data['site_name'], $url);
            ?>
            <br clear="all" /><br clear="all" />
            <input type="submit" class="btn btn-primary" value="<?php echo $this->_('remove_site', 'sites'); ?>" />
            <?php echo $this->form()->closeTag() ?>      
      </div>

    </div>
</div>    