<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('admin', 'cp'); ?> <small><?php echo $this->_('settings', 'cp'); ?></small></h1>
    </div>
      <div class="row">
        <div class="col-sm-3 col-md-3 sidebar">
            <?php echo $this->render('cp/global/_sidebar'); ?>
      </div>
      <div class="col-sm-9 col-md-9">
            <?php echo $this->render('partials/_tabs'); ?>    
        <p>fdsa</p>
        <p>fdsa</p>
        <p>fdsa</p>
        <p>fdsa</p>
        <p>fdsa</p>
      </div>

    </div>
</div>    