<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('admin', 'cp'); ?> <small><?php echo $this->_('settings', 'cp'); ?></small></h1>
    </div>
      <div class="row">
        <div class="col-sm-3 col-md-3 sidebar">
            <?php echo $this->render('cp/global/_sidebar'); ?>
      </div>
      <div class="col-sm-9 col-md-9">
        <?php echo $this->render('partials/_tabs'); ?>    
            
        <?php
        $form = $this->form;
        $form->setAttribute('id', 'SettingsForm');
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();
        
        echo $this->form()->openTag($form);
        $csrf = $form->get('_x');
        echo $this->formRow($csrf);
        echo $this->render('partials/_form/'.$this->section);
        ?>
        
        
        <div class="form-group">
        	<div class="col-xs-offset-2 col-xs-10">
        		<button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo $this->_('submit', 'app'); ?></button>
        	</div>
        </div>
        
        <?php echo $this->form()->closeTag() ?>
                
      </div>

    </div>
</div>    