<ul>
	<?php if($this->CheckPermission('manage_users')):?>
		<li><a href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'users','action'=>'index'), null, TRUE); ?>" class="<?php echo ($this->active_sub == 'users' ? 'active' : ''); ?>">Projects</a></li>
	<?php endif; ?>
	<?php if($this->CheckPermission('manage_roles')):?>
		<li><a href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'roles','action'=>'index'), null, TRUE); ?>" class="<?php echo ($this->active_sub == 'roles' ? 'active' : ''); ?>">Tasks</a></li>
	<?php endif; ?>
	<li><a href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'settings','action'=>'global'), null, TRUE); ?>" class=" <?php echo ($this->active_sub == 'global' ? 'active' : ''); ?>">Time Tracker</a></li>
	<li><a href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'import','action'=>'index'), null, TRUE); ?>" class="<?php echo ($this->active_sub == 'import' ? 'active' : ''); ?>">Files</a></li>
	<li><a href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'settings','action'=>'email'), null, TRUE); ?>" class="<?php echo ($this->active_sub == 'emails' ? 'active' : ''); ?>">Admin</a></li>
	<li><a href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'ips','action'=>'index'), null, TRUE); ?>" class="last <?php echo ($this->active_sub == 'ips' ? 'active' : ''); ?>">Basics</a></li>
</ul>