<div class="content_headers" style="padding-top:0px;">
	<div class="project_header">Edit Project</div>	
</div>
<div class="back_link_content">
	<a href="<?php echo $this->url('projects/view', array('project_id' => $this->project_data['id'])); ?>" title="Back to <?php echo $this->project_data['name']; ?>">
		Back to <?php echo $this->project_data['name']; ?>	
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to '.$this->project_data['name']);?></div>
</div>
<br clear="all" />
<?php 
$options = array('form' => $this->form, 'id' => $this->id);
echo $this->partial('pm/projects/partials/form', $options); 
?>