<div class="content_headers" style="padding-top:0px;">
	<div class="project_header">Delete Project: <?php echo $this->project['name']?></div>	
</div>
<div class="attention png_bg">
Are you sure you want to remove "<?php echo $this->project['name']?>"? This can not be undone...
</div>

<p>
<?php 
$form = $this->form;
$form->setAttribute('id', 'project_form');
$form->setAttribute('action', $this->url('projects/remove', array('project_id' => $this->project['id'])));
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
	<?php $field = $form->get('confirm'); echo $this->formRow($field); ?> <?php $field = $form->get('fail'); echo $this->formRow($field); ?>
<?php echo $this->form()->closeTag() ?>

<h2>Project Details</h2>
<p>
<?php echo $this->project['name']?> contains:
<br />
<?php echo $this->task_count; ?> Tasks<br />
<?php echo $this->file_count; ?> Files

</p>