<?php 
$partials = array(
		'pm/admin/index/users',
		'pm/admin/index/reports',
		'pm/admin/index/configure',
);
$partials = $this->DispatchRouteEvents($partials, array());
?>
<div class="content_headers" style="padding-top:0px;">

	<div class="project_header">Viewing Project: <?php echo $this->project['name']; ?></div>	
		<?php if($this->CheckPermission('track_time')):?>
		<div class="actions">
			<a href="<?php echo $this->url('timers/view', array('type' => 'project', 'id' => $this->id), null, TRUE); ?>" title="Timer" rel="facebox">
				<?php echo $this->InteractIcon('timer', 'Timer');?>
				<div class="action_text">Timer</div>
			</a>
		</div>	
		<?php endif; ?>	
					
		<?php if($this->CheckPermission('manage_projects')):?>
		<div class="actions">
			<a href="<?php echo $this->url('projects/remove', array('company_id' => FALSE, 'project_id' => $this->id), null, TRUE); ?>" rel="facebox" title="Delete">
				<?php echo $this->InteractIcon('cross', 'Delete');?>
				<div class="action_text">Delete</div>
			</a>
		</div>		
		<div class="actions">
			<a href="<?php echo $this->url('projects/edit', array('company_id' => FALSE, 'project_id' => $this->id), null, TRUE); ?>">
				<?php echo $this->InteractIcon('pencil', 'Edit');?>
				<div class="action_text">Edit</div>
			</a> 
		</div>
		<?php endif; ?>		
</div>

<?php echo $this->Breadcrumb('project', $this->id); ?>

<div class="item_details">
    <div class="items">
    	<p>
			<span class="bold">Company:</span> <a href="<?php echo $this->url('companies/view', array('company_id' => $this->project['company_id']), null, TRUE); ?>"><?php echo $this->project['company_name']; ?></a><br />
			<span class="bold">Status:</span> <?php echo $this->ProjectStatus($this->project['status']); ?><br />
			<span class="bold">Priority:</span> <?php echo $this->ProjectPriority($this->project['priority']); ?><br />
			<span class="bold">Type:</span> <?php echo $this->ProjectType($this->project['type']);?>    	
    	</p>
    </div>
    <div class="items" style="padding-left:10px;">
    	<p>
			<span class="bold">Started:</span> <?php echo $this->RelativeDate($this->project['start_date']); ?><br />
			<span class="bold">Ended:</span> <?php echo $this->RelativeDate($this->project['end_date']); ?>  <br />	
    	</p>
    </div>
    
    <?php if($this->CheckPermission('view_time')): ?>
    <div class="items" >
    	<p>
			<span class="bold">Estimated:</span> <?php echo number_format($this->estimated_time, 2); ?>   <br />
			<span class="bold">Hours Remaining:</span> <?php echo number_format($this->estimated_time, 2); ?>  <br />  
			<span class="bold">Unbillable Time:</span> <?php echo number_format($this->estimated_time, 2); ?>    
    	</p>
    </div>

    <div class="items" style="padding-left:10px;">
		<?php 
			$options = array('hours' => $this->hours, 'type' => 'project', 'id' => $this->id);
			echo $this->partial('pm/times/partials/hour_status', $options); 		
		?>
    </div>
    <?php endif; ?>
</div>

<br clear="all" />

<?php if($this->project['description'] != ''): ?>
<h2>Description:</h2>
<?php echo $this->FormatHtml($this->project['description']); ?>
<?php endif; ?>

<div class="content_headers">
	<div class="projteam_header">Team Members</div>		
	<?php if($this->CheckPermission('manage_projects') || $this->identity == $this->project['creator']): ?>
	<div class="actions">
		<a href="<?php echo $this->url('projects/manage-team', array('company_id' => FALSE,'controller' => 'projects','action'=>'manage-team', 'project' => $this->id), null, TRUE); ?>">
			<?php echo $this->InteractIcon('pencil', 'Manage Team');?>
			<div class="action_text">Manage Team</div>
		</a>
	</div>
	<?php endif; ?>
</div>
<?php 
if($this->proj_team):
	$options = array('proj_team' => $this->proj_team);
	echo $this->partial('pm/projects/partials/proj_team', $options);

else: 
?>
<div class="information png_bg">There aren't any team members on this project yet. Want to <a href="<?php echo $this->url(array('module' => 'pm','controller' => 'projects','action'=>'manage-team', 'project' => $this->id), null, TRUE); ?>">add</a> one?</div>
<?php 
endif;
?>

<?php if($this->CheckPermission('view_tasks')): ?>
	<div class="content_headers">
		<div class="task_header">Tasks</div>				
		<div class="actions">
			<a href="<?php echo $this->url('tasks/all', array('project_id' => $this->id)); ?>" title="View All">
				<?php echo $this->InteractIcon('view-all', 'View All');?> 
				<div class="action_text">View All</div>
			</a>
		</div>		
		<?php if($this->CheckPermission('manage_tasks') || $this->user_is_on_team): ?>
		
		<div class="actions">
			<a href="<?php echo $this->url('tasks/add', array('project_id' => $this->id)); ?>" title="Add Task">
				<?php echo $this->InteractIcon('add', 'Add Task');?>  
				<div class="action_text">Add Task</div>
			</a>
		</div>
		<?php endif; ?>		
	</div>
	<?php 
	if($this->tasks):
		$options = array('tasks' => $this->tasks, 'enable_due' => 'yes', 'enable_assigned' => 'yes', 'enable_completion' => 'yes');
		echo $this->partial('pm/tasks/partials/tasks', $options);
	
	else: 
	?>
	<div class="information png_bg">There aren't any tasks setup yet. <?php if($this->CheckPermission('manage_tasks')): ?>Want to <a href="<?php echo $this->url('tasks/add', array('project_id' => $this->id)); ?>">add</a> one?<?php endif; ?></div>
	<?php 
	endif;
endif;
?>

<?php if($this->CheckPermission('view_files')): ?>
	<div class="content_headers">
		<div class="file_header">Files</div>		
		<div class="actions">
			<a href="<?php echo $this->url('files/all', array('type' => 'project', 'id' => $this->id)); ?>" title="View All">
				<?php echo $this->InteractIcon('view-all', 'View All');?>  
				<div class="action_text">View All</div>
			</a>
		</div>		
		<?php if($this->CheckPermission('manage_files')): ?>
		<div class="actions">
			<a href="<?php echo $this->url('files/add', array('type'=>'project', 'id' => $this->id)); ?>" rel="facebox" title="Add File">
				<?php echo $this->InteractIcon('add', 'Add File');?> 
				<div class="action_text">Add File</div>
			</a>
		</div>
		<?php endif; ?>		
	</div>
	<?php 
	if($this->files):
		$options = array('files' => $this->files, 'enable_task' => 'yes');
		echo $this->partial('pm/files/partials/files', $options); 
	else: 
	?>
	<div class="information png_bg">There aren't any files uploaded yet. <?php if($this->CheckPermission('manage_files')): ?>Want to <a href="<?php echo $this->url('files/add', array('type'=>'project', 'id' => $this->id)); ?>" rel="facebox" >add</a> one?<?php endif; ?></div>
	<?php 
	endif;
endif;
?>

<div class="content_headers">
	<div class="note_header">Notes</div>	
	<div class="actions">
		<a href="<?php echo $this->url('notes/all', array('type'=>'project', 'id' => $this->id)); ?>" title="View All">
			<?php echo $this->InteractIcon('view-all', 'View All');?>  
			<div class="action_text">View All</div>
		</a>
	</div>
	<?php if($this->user_is_on_team): ?>
	<div class="actions">
		<a rel="facebox" href="<?php echo $this->url('notes/add', array('type'=>'project', 'id' => $this->id)); ?>" title="Add Note">
			<?php echo $this->InteractIcon('add', 'Add Note');?>  
			<div class="action_text">Add Note</div>
		</a>
	</div>
	<?php endif; ?>
</div>
<?php 
if($this->notes):
	$options = array('notes' => $this->notes, 'facebox' => 'yes', 'enable_task' => 'yes');
	echo $this->partial('pm/notes/partials/notes', $options); 
else: 
?>
<div class="information png_bg">There aren't any notes added yet. Want to <a href="<?php echo $this->url('notes/add', array('type'=>'project', 'id' => $this->id)); ?>" rel="facebox">add</a> one?</div>
<?php 
endif;
?>

<div class="content_headers">
	<div class="bookmark_header">Bookmarks</div>	
	<div class="actions">
		<a href="<?php echo $this->url('bookmarks/all', array('type' => 'project', 'id' => $this->id)); ?>" title="View All">
			<?php echo $this->InteractIcon('view-all', 'View All');?>  
			<div class="action_text">View All</div>
		</a>
	</div>	
	<?php if($this->user_is_on_team):?>	
	<div class="actions">
		<a rel="facebox" href="<?php echo $this->url('bookmarks/add', array('type'=>'project', 'id' => $this->id)); ?>"  title="Add Bookmark">
			<?php echo $this->InteractIcon('add', 'Add Bookmark');?>  
			<div class="action_text">Add Bookmark</div>
		</a>
	</div>
	<?php endif; ?>
</div>
<?php 
if($this->bookmarks):
	$options = array('bookmarks' => $this->bookmarks, 'facebox' => 'yes', 'enable_task' => 'yes');
	echo $this->partial('pm/bookmarks/partials/bookmarks', $options); 
else: 
?>
<div class="information png_bg">There aren't any bookmarks added yet. Want to <a href="<?php echo $this->url('bookmarks/add', array('type' => 'project', 'id' => $this->id), null, TRUE); ?>" rel="facebox">add</a> one?</div>
<?php 
endif;
?>

<?php if($this->CheckPermission('view_time')): ?>
	<div class="content_headers">
		<div class="timetracker_header">Timetracker</div>		
		<div class="actions">
			<a href="<?php echo $this->url('times/view', array('type' => 'project','id' => $this->id)); ?>" title="View All">
				<?php echo $this->InteractIcon('view-all', 'View All');?> 
				<div class="action_text">View All</div>
			</a>
		</div>	
	</div>
	<?php 
	if($this->times): 
		$options = array('times' => $this->times, 'enable_task' => 'yes', 'enable_date' => 'yes');
		echo $this->partial('pm/times/partials/times', $options); 
	else: 
	?>
	<div class="information png_bg">There aren't any pending times added yet.</div>
	<?php 
	endif;
endif;
?>
