<div class="content_headers" style="padding-top:0px;">
	<div class="invoice_header">Add Invoice</div>
</div>
<div class="back_link_content">
	<a href="<?php echo $this->url('companies/view', array('company_id'=>$this->company_data['id'])); ?>" title="Back to <?php echo $this->company_data['name']; ?>">
		Back to <?php echo $this->company_data['name']; ?>	
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to '.$this->company_data['name']);?></div>
</div>
<br clear="all" />
<?php 
$options = array('form' => $this->form, 'form_action' => $this->form_action, 'company_data' => $this->company_data, 'time_data' => $this->time_data);
echo $this->partial('pm/invoices/partials/form', $options);
?>