<?php if($this->company): ?>
<div class="content_headers" style="padding-top:0px;">

	<div class="contact_header"><?php echo $this->company['name']; ?> Contacts</div>
		
		<div class="actions">
			<a href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'docs','action'=>'contacts', 'page' => 'main'), null, TRUE); ?>" rel="facebox" title="Add Contacts">
				<?php echo $this->InteractIcon('help', 'About Contacts');?>
				<div class="action_text">Help</div>
			</a>
		</div>			
		<?php if($this->CheckPermission('manage_company_contacts')):?>	
		<div class="actions">
			<a href="<?php echo $this->url('contacts/add', array('company_id' => $this->company['id'])); ?>" title="Add">
				<?php echo $this->InteractIcon('add', 'Add New Contact');?>
				<div class="action_text">Add New Contact</div>
			</a> 
		</div>
		<?php endif; ?>	
</div>

	<div class="back_link_content">
		<a href="<?php echo $this->url('companies/view', array('module' => 'pm','controller'=>'companies','action'=>'view', 'company_id'=>$this->company['id']), null, TRUE); ?>" title="Back to <?php echo $this->company['name'];?>">
			Back to <?php echo $this->company['name']; ?>	
		</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to '.$this->company['name']);?></div>
	</div>
	<br clear="all" />
<?php else: ?>


<?php endif; ?>		
<?php 
if($this->contacts): 

	$options = array('contacts' => $this->contacts, 'enable_actions' => 'yes', 'facebox' => 'yes');
	echo $this->partial('pm/contacts/partials/contacts', $options);

else: ?>

<div class="information png_bg">There aren't contacts added yet. Want to <a href="<?php echo $this->url('contacts/add', array('company_id' => $this->company['id']), null, FALSE); ?>">add</a> one?.</div>

<?php endif; ?>