<div class="content_headers" style="padding-top:0px;">
	<div class="project_header">Delete Invoice: <?php echo $this->invoice_data['invoice_number']?></div>	
</div>
<div class="attention png_bg">
Are you sure you want to remove "<?php echo $this->invoice_data['invoice_number']?>"? This can not be undone...
</div>

<?php 
$form = $this->form;
$form->setAttribute('id', 'remove_invoice_form');
$form->setAttribute('action', $this->url('invoices/remove', array('invoice_id' => $this->invoice_data['id'])));
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
	<?php $field = $form->get('confirm'); echo $this->formRow($field); ?> <?php $field = $form->get('fail'); echo $this->formRow($field); ?>
<?php echo $this->form()->closeTag() ?>