<div class="content_headers" style="padding-top:0px;">
	<div class="users_header">Add User</div>	
</div>
<?php 
$form = $this->form;
$form->setAttribute('id', 'user_form');
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
<div id="form_tabs">
		
		<p>
			<label for="first_name">First Name</label>
			<?php $field = $form->get('first_name'); echo $this->formRow($field); ?>
		</p>				
		
		<p>
			<label for="last_name">Last Name</label>
			<?php $field = $form->get('last_name'); echo $this->formRow($field); ?>
		</p>			
		
		<p>
			<label for="email">Email</label>
			<?php $field = $form->get('email'); echo $this->formRow($field); ?>
		</p>
		
		<p class="user_role_boxes">
		<?php $field = $form->get('user_roles'); echo $this->formRow($field); ?>		
		</p>		
		

		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>				
	</div>	
<?php echo $this->ConfirmPageUnload('#user_form')?>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
jQuery(document).ready(function($){
	$("#user_form").validate({
		rules: {
			first_name: "required",
			last_name: "required",
			email: {
				required: true,
				email: true
			},
			password: {
				required: true,
				minlength: 5
			},
			confirm_password: {
				required: true,
				equalTo: "#password",
				minlength: 5
			},
			user_roles: "required"
		},
		messages: {
			first_name: "Please enter a first name",
			last_name: "Please enter a last name",
			email: {
				required: "Please enter an email",
				email: "Please enter a valid email address"
			},
			password: {
				required: "Please enter a password",
				minlength: "Your password must be at least 5 characters long"
			},
			confirm_password: {
				required: "Please confirm your password",
				equalTo: "Please enter the same password as above",
				minlength: "Your password must be at least 5 characters long"
			},
			user_roles: "Please choose the roles for the user"
		}
	});	
	$.validator.setDefaults({
		submitHandler: function() { return confirm("submitted!"); }
	});	
});
</script>