<div class="content_headers" style="padding-top: 0px;">

	<div class="users_header">Users</div>
	<div class="actions">
		<a
			href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'docs','action'=>'users', 'page' => 'main'), null, TRUE); ?>"
			rel="facebox" title="Add Project">
				<?php echo $this->InteractIcon('help', 'About Users');?>
				<div class="action_text">Help</div>
		</a>
	</div>			
		<?php if($this->CheckPermission('manage_users')):?>
		<div class="actions">
		<a href="<?php echo $this->url('users/invite'); ?>"
			title="Invite User" rel="facebox">
				<?php echo $this->InteractIcon('add', 'Invite User');?>
				<div class="action_text">Invite User</div>
		</a>
	</div>
		<?php endif; ?>	
</div>


<?php
if ($this->users) :
    
    $options = array(
        'users' => $this->users,
        'enable_actions' => 'yes',
        'identity' => $this->identity
    );
    echo $this->partial('host-manager/users/partials/users', $options);
 

else :
    ?>

<div class="information png_bg">
	There aren't users added yet. Want to <a
		href="<?php echo $this->url('users/invite'); ?>" rel="facebox">add</a>
	one?.
</div>

<?php endif; ?>

<div class="content_headers" style="padding-top: 0px;">
	<div class="invites_header">Invites</div>
</div>
<?php
if ($this->invites) :
    
    $options = array(
        'invites' => $this->invites
    );
    echo $this->partial('host-manager/accounts/partials/invites', $options);
 

else :
    ?>

<div class="information png_bg">
	There aren't invites pending. Want to <a
		href="<?php echo $this->url('users/invite'); ?>" rel="facebox">invite</a>
	someone?.
</div>

<?php endif; ?>			