<div class="content_headers" style="padding-top:0px;">
	<div class="user_role_header">Remove User: <?php echo $this->user['first_name']?> <?php echo $this->user['last_name']?></div>	
</div>

<?php 
if($this->identity == $this->user['id']): ?>
<div class="fail png_bg">
You can't remove yourself...
</div>
<?php else: ?>
<div class="attention png_bg">
Are you sure you want to remove <?php echo $this->user['first_name']?> <?php echo $this->user['last_name']?>? This can not be undone...
</div>

<p>
<?php 
$form = $this->form;
$form->setAttribute('id', 'user_form');
$form->setAttribute('action', $this->url('users/remove', array('user_id' => $this->user['id'])));
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
	<?php $field = $form->get('confirm'); echo $this->formRow($field); ?> <?php $field = $form->get('fail'); echo $this->formRow($field); ?>
<?php echo $this->form()->closeTag() ?>
</p>

<h2>User Details</h2>
<p>
<a href="/pm/users/view/id/<?php echo $this->id; ?>"><?php echo $this->user['first_name']?> <?php echo $this->user['last_name']?></a> contains:
<br />
<?php echo $this->projects_owned_count; ?> Projects Owned<br />
<?php echo $this->tasks_owned_count; ?> Tasks Owned<br />
<?php echo $this->files_owned_count; ?> Files Owned

</p>

<?php endif; ?>