<h1><?php echo $this->_('forgot_password', 'app'); ?></h1>	
<?php 

$form = $this->form;
$form->setAttribute('id', 'sumbitForm');
$form->prepare();

if(is_array($this->messages) && count($this->messages) >= 1)
{
	foreach($this->messages AS $message) 
	{
		echo '<div class="success large png_bg">'.$message.'</div>';
	}
} else {
	
	echo '<div class="information large png_bg">'.$this->_('forgot_password_instructions', 'app').'</div> ';
}

echo $this->form()->openTag($form); 
		$csrf = $form->get('_x');
		echo $this->formRow($csrf); ?>				  
		<p><label>Email</label>
		<?php 
		$email = $form->get('email');
		echo $this->formRow($email); ?>		
	  </p>
	  
	  <p><input type="submit" name="Submit" id="button" value="Submit"  class="button"/></p>
		<a href="<?php echo $this->url('login');?>" class="blueLink"><?php echo $this->_('back_to_login', 'app'); ?></a>
<?php echo $this->form()->closeTag() ?>
	
<script type="text/javascript">
$.validator.setDefaults({
	//submitHandler: function() { alert("submitted!"); }
});

$().ready(function() {

	$("#email").focus();
	$("#sumbitForm").validate({
		rules: {
			email: "<?php echo $this->_('required', 'app'); ?>"
		},
		messages: {
			email: "<?php echo $this->_('js_email_validation_message', 'app'); ?>"
		}
	});

});

</script>