<?php $settings_form = $form; ?>
<fieldset>
<div class="row">
	<div class="form-group">
		<label for="max_db_backups" class="control-label col-sm-3"><?php echo $this->_('max_db_backups', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('max_db_backups');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('max_db_backups_instructions', 'sites'); ?></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group">
		<label for="db_backup_alert_threshold" class="control-label col-sm-3"><?php echo $this->_('db_backup_alert_threshold', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('db_backup_alert_threshold');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('db_backup_alert_threshold_instructions', 'sites'); ?></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group">
		<label for="db_backup_method" class="control-label col-sm-3"><?php echo $this->_('db_backup_method', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('db_backup_method');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('db_backup_method_instructions', 'sites'); ?></div>
		</div>
	</div>
</div>
<div class="row" id="mysqldump_command_wrap" style="display:none;">
	<div class="form-group">
		<label for="mysqldump_command" class="control-label col-sm-3"><?php echo $this->_('mysqldump_command', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('mysqldump_command');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('mysqldump_command_instructions', 'sites'); ?></div>
		</div>
	</div>
</div>
<div class="row" id="php_backup_method_select_chunk_limit_wrap" style="display:none;">
	<div class="form-group">
		<label for="php_backup_method_select_chunk_limit" class="control-label col-sm-3"><?php echo $this->_('php_backup_method_select_chunk_limit', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('php_backup_method_select_chunk_limit');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('php_backup_method_select_chunk_limit_instructions', 'sites'); ?></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group">
		<label for="db_restore_method" class="control-label col-sm-3"><?php echo $this->_('db_restore_method', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('db_restore_method');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('db_restore_method_instructions', 'sites'); ?></div>
		</div>
	</div>
</div>
<div class="row" id="mysqlcli_command_wrap" style="display:none;">
	<div class="form-group">
		<label for="mysqlcli_command" class="control-label col-sm-3"><?php echo $this->_('mysqlcli_command', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('mysqlcli_command');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('mysqlcli_command_instructions', 'sites'); ?></div>
		</div>
	</div>
</div>

</fieldset>

<fieldset>
    <legend><?php echo $this->_('config_ignore_sql', 'sites')?></legend>
    
    <div class="row">
    	<div class="form-group">
    		<label for="db_backup_ignore_tables" class="control-label col-sm-3"><?php echo $this->_('db_backup_ignore_tables', 'sites')?></label>
    		<div class="col-sm-9">
                <?php
                $field = $form->get('db_backup_ignore_tables');
                echo $this->formRow($field);
                ?>
    			<div class="help-block small"><?php echo $this->_('db_backup_ignore_tables_instructions', 'sites'); ?></div>
    		</div>
    	</div>
    </div>
    
    <div class="row">
    	<div class="form-group">
    		<label for="db_backup_ignore_table_data" class="control-label col-sm-3"><?php echo $this->_('db_backup_ignore_table_data', 'sites')?></label>
    		<div class="col-sm-9">
                <?php
                $field = $form->get('db_backup_ignore_table_data');
                echo $this->formRow($field);
                ?>
    			<div class="help-block small"><?php echo $this->_('db_backup_ignore_table_data_instructions', 'sites'); ?></div>
    		</div>
    	</div>
    </div>    
</fieldset> 

<fieldset>
    <legend><?php echo $this->_('config_extra_archive_sql', 'sites')?></legend>
    <div class="row">
    	<div class="form-group">
    		<label for="db_backup_archive_pre_sql" class="control-label col-sm-3"><?php echo $this->_('db_backup_archive_pre_sql', 'sites')?></label>
    		<div class="col-sm-9">
                <?php
                $field = $form->get('db_backup_archive_pre_sql');
                echo $this->formRow($field);
                ?>
    			<div class="help-block small"><?php echo $this->_('db_backup_archive_pre_sql_instructions', 'sites'); ?></div>
    		</div>
    	</div>
    </div>
    
    <div class="row">
    	<div class="form-group">
    		<label for="db_backup_archive_post_sql" class="control-label col-sm-3"><?php echo $this->_('db_backup_archive_post_sql', 'sites')?></label>
    		<div class="col-sm-9">
                <?php
                $field = $form->get('db_backup_archive_post_sql');
                echo $this->formRow($field);
                ?>
    			<div class="help-block small"><?php echo $this->_('db_backup_archive_post_sql_instructions', 'sites'); ?></div>
    		</div>
    	</div>
    </div>  
</fieldset>

<fieldset>
    <legend><?php echo $this->_('config_execute_sql', 'sites')?></legend>
    <div class="row">
    	<div class="form-group">
    		<label for="db_backup_execute_pre_sql" class="control-label col-sm-3"><?php echo $this->_('db_backup_execute_pre_sql', 'sites')?></label>
    		<div class="col-sm-9">
                <?php
                $field = $form->get('db_backup_execute_pre_sql');
                echo $this->formRow($field);
                ?>
    			<div class="help-block small"><?php echo $this->_('db_backup_execute_pre_sql_instructions', 'sites'); ?></div>
    		</div>
    	</div>
    </div>
    
    <div class="row">
    	<div class="form-group">
    		<label for="db_backup_execute_post_sql" class="control-label col-sm-3"><?php echo $this->_('db_backup_execute_post_sql', 'sites')?></label>
    		<div class="col-sm-9">
                <?php
                $field = $form->get('db_backup_execute_post_sql');
                echo $this->formRow($field);
                ?>
    			<div class="help-block small"><?php echo $this->_('db_backup_execute_post_sql_instructions', 'sites'); ?></div>
    		</div>
    	</div>
    </div>  
</fieldset>