<?php $settings_form = $form; ?>
<fieldset>
<div class="row">
	<div class="form-group">
		<label for="max_file_backups" class="control-label col-sm-3"><?php echo $this->_('max_file_backups', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('max_file_backups');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('max_file_backups_instructions', 'sites'); ?></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group">
		<label for="file_backup_alert_threshold" class="control-label col-sm-3"><?php echo $this->_('file_backup_alert_threshold', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('file_backup_alert_threshold');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('file_backup_alert_threshold_instructions', 'sites'); ?></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group">
		<label for="backup_file_location" class="control-label col-sm-3"><?php echo $this->_('backup_file_location', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('backup_file_location');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('backup_file_location_instructions', 'sites'); ?></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group">
		<label for="exclude_paths" class="control-label col-sm-3"><?php echo $this->_('exclude_paths', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('exclude_paths');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('exclude_paths_instructions', 'sites'); ?></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group">
		<label for="regex_file_exclude" class="control-label col-sm-3"><?php echo $this->_('regex_file_exclude', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('regex_file_exclude');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('regex_file_exclude_instructions', 'sites'); ?></div>
		</div>
	</div>
</div>
</fieldset>