<?php $settings_form = $form; ?>
<fieldset>
<div class="row">
	<div class="form-group <?php if($form_errors['working_directory']): ?>has-error<?php endif; ?>">
		<label for="working_directory" class="control-label col-sm-3"><?php echo $this->_('working_directory', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('working_directory');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('working_directory_instructions', 'sites'); ?></div>
			<?php echo $this->m62FormErrors($form_errors['working_directory']); ?>
		</div>
	</div>
</div>

<div class="row">
	<div class="form-group <?php if($form_errors['cron_query_key']): ?>has-error<?php endif; ?>">
		<label for="cron_query_key" class="control-label col-sm-3"><?php echo $this->_('cron_query_key', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('cron_query_key');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('cron_query_key_instructions', 'sites'); ?></div>
			<?php echo $this->m62FormErrors($form_errors['cron_query_key']); ?>
		</div>
	</div>
</div>

<div class="row">
	<div class="form-group <?php if($form_errors['dashboard_recent_total']): ?>has-error<?php endif; ?>">
		<label for="dashboard_recent_total" class="control-label col-sm-3"><?php echo $this->_('dashboard_recent_total', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('dashboard_recent_total');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('dashboard_recent_total_instructions', 'sites'); ?></div>
			<?php echo $this->m62FormErrors($form_errors['dashboard_recent_total']); ?>
		</div>
	</div>
</div>

<div class="row">
	<div class="form-group <?php if($form_errors['auto_threshold']): ?>has-error<?php endif; ?>">
		<label for="auto_threshold" class="control-label col-sm-3"><?php echo $this->_('auto_threshold', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('auto_threshold');
            echo $this->formRow($field);
            ?>
		<div class="help-block small"><?php echo $this->_('auto_threshold_instructions', 'sites'); ?></div>
			<?php echo $this->m62FormErrors($form_errors['auto_threshold']); ?>
		</div>
	</div>
</div>

<div class="row" id="auto_threshold_custom_wrap" style="display:none;">
	<div class="form-group <?php if($form_errors['auto_threshold_custom']): ?>has-error<?php endif; ?>">
		<label for="auto_threshold_custom" class="control-label col-sm-3"><?php echo $this->_('auto_threshold_custom', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('auto_threshold_custom');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('auto_threshold_custom_instructions', 'sites'); ?></div>
			<?php echo $this->m62FormErrors($form_errors['auto_threshold_custom']); ?>
		</div>
	</div>
</div>

<div class="row">
	<div class="form-group <?php if($form_errors['allow_duplicates']): ?>has-error<?php endif; ?>">
    	<label class="control-label col-sm-3" for="allow_duplicates"><?php echo $this->_('allow_duplicates', 'sites')?></label>
    	<div class="col-sm-9">
            <?php
            $field = $form->get('allow_duplicates');
            echo $this->formRow($field);
            ?>
            <span class="small"><?php echo $this->_('allow_duplicates_instructions', 'sites'); ?></span>
			<?php echo $this->m62FormErrors($form_errors['allow_duplicates']); ?>
        </div>
    </div>
</div>

<div class="row">
	<div class="form-group <?php if($form_errors['date_format']): ?>has-error<?php endif; ?>">
		<label for="date_format" class="control-label col-sm-3"><?php echo $this->_('date_format', 'sites')?></label>
		<div class="col-sm-9">
            <?php
            $field = $form->get('date_format');
            echo $this->formRow($field);
            ?>
			<div class="help-block small"><?php echo $this->_('date_format_instructions', 'sites'); ?></div>
			<?php echo $this->m62FormErrors($form_errors['date_format']); ?>
		</div>
	</div>
</div>

<div class="row">
	<div class="form-group <?php if($form_errors['relative_time']): ?>has-error<?php endif; ?>">
    	<label class="control-label col-sm-3" for="relative_time"><?php echo $this->_('relative_time', 'sites'); ?></label>
    	<div class="col-sm-9">
            <label class="small"><?php
            $field = $form->get('relative_time');
            echo $this->formRow($field);
            ?>
            <?php echo $this->_('relative_time_instructions', 'sites'); ?></label>
			<?php echo $this->m62FormErrors($form_errors['relative_time']); ?>
        </div>
    </div>
</div>
</fieldset>