<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Projects</div>
</div>
<p>
<?php if($this->CheckPermission('manage_projects')):?>
This page lists all the projects in the system. 
<?php else: ?>
This page lists all the projects you're assigned to. 
<?php endif; ?>
</p>

<h4>Filtering</h4>
<p>
You can filter by the status type by using the submenu. From here you can:
</p>
<h4>Actions</h4>

<p>
	<?php if($this->CheckPermission('manage_projects')):?>
		<?php echo $this->InteractIcon('add', 'Add Project');?> Add new projects
		<br /><?php echo $this->InteractIcon('pencil', 'Edit');?> Edit projects
		<br /><?php echo $this->InteractIcon('cross', 'Delete');?> Remove projects<br />
	<?php endif; ?>
	<?php echo $this->InteractIcon('user', 'Project Team');?> View Project Team
	<br /><?php echo $this->InteractIcon('folder', 'Project Files');?> View Project Files
	
</p>