<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Project View</div>
</div>
<p>
This page lists all the details on a given project. Depending on the parent companies type (Internal, Client, etc) the below options
may vary.
</p>

<h4>Team Members</h4>
<p>
This lists all the MojiTrac users that are associated with the project. Every user here gets notified on all activity with the project
as well as being available for task assignments and the ability to interact with the various components.
</p>

<h4>Tasks</h4>
<p>
Want someone to do something for the project? You set that up here. 
</p>

<h4>Files</h4>
<p>
Depending on the project there may be a need to share files and communicate; that's what the files module is for. 
</p>

<h4>Notes</h4>
<p>
Have a quick little idea you want to share? Create a note and every member of the project team will have access to it.
</p>

<h4>Bookmarks</h4>
<p>
All those URLs that everyone always needs should be placed here.
</p>

<?php if($this->CheckPermission('view_time')): ?>
<h4>Time Tracker</h4>
<p>
All the time that's associated with a project, from everyone on the project team, is displayed here. 
</p>
<?php endif; ?>