<div class="content_headers">
	<div class="freshbooks_header">Freshbooks</div>	
</div>
<dl>
	<dt><a href="<?php echo $this->url('freshbooks-settings/link-account', array('module' => 'pm','controller' => 'users','action'=>'index'), null, TRUE); ?>">Configure Credentials</a></dt>
	<dd>The Freshbooks account to link MojiTrac to is setup here.</dd>
	<dt><a href="<?php echo $this->url('roles', array('module' => 'pm','controller' => 'roles','action'=>'index'), null, TRUE); ?>">Clients From Freshbooks</a></dt>
	<dd>Which clients should MojiTrac sync from Freshbooks?</dd>
	<dt><a href="<?php echo $this->url('roles', array('module' => 'pm','controller' => 'roles','action'=>'index'), null, TRUE); ?>">Clients to Freshbooks</a></dt>
	<dd>Which clients should MojiTrac sync to Freshbooks?</dd>
</dl>