<div class="content_headers" style="padding-top:0px;">
	<div class="task_header">
	<?php if($this->project_data['id']): ?>
	Project Tasks for: <?php echo $this->project_data['name']; ?>
	<?php else: ?>
	Tasks
	<?php endif; ?>
	</div>
	<?php if($this->CheckPermission('manage_projects')):?>
	<div class="actions">
		<a href="<?php echo $this->url('tasks/add', array('module' => 'pm','controller' => 'tasks','action'=>'add'), null, TRUE); ?>" title="Add Task">
			<?php echo $this->InteractIcon('add', 'Add Task');?>
			<div class="action_text">Add Task</div>
		</a>
	</div>
	<?php endif; ?>		
</div>

<?php if($this->project_data['id']): ?>
<div class="back_link_content">
	<a href="<?php echo $this->url('projects/view', array('module' => 'pm','controller'=>'projects','action'=>'view', 'id'=>$this->project_data['id']), null, TRUE); ?>" title="Back to <?php echo $this->project_data['name']; ?>">
		Back to <?php echo $this->project_data['name']; ?>	
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to '.$this->project_data['name']);?></div>
</div>
<br clear="all" />
<?php endif;?>

<?php 
if($this->tasks):
	$options = array('tasks' => $this->tasks, 'enable_actions' => 'yes', 'enable_due' => 'yes', 'enable_assigned' => 'yes', 'enable_completion' => 'yes');
	echo $this->partial('pm/tasks/partials/tasks', $options); 
else: 
?>

<div class="information png_bg">There aren't any tasks setup yet. Want to <a href="<?php echo $this->url('tasks/add', array('module' => 'pm','controller' => 'tasks','action'=>'add'), null, TRUE); ?>">add</a> one?.</div>

<?php endif; ?>