<div class="content_headers" style="padding-top:0px;">

	<div class="task_header">Viewing Task: <?php echo $this->task['name']; ?></div>
		<!-- 
		<div class="actions">
			<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'tasks','action'=>'ical', 'id' => $this->id), null, TRUE); ?>" title="Export Time">
				<?php echo $this->InteractIcon('save_disk', 'Export');?>
				<div class="action_text">Export</div>
			</a>
		</div>
		 -->
		
		<?php if($this->CheckPermission('track_time')):?>
		<div class="actions">
			<a href="<?php echo $this->url('timers/view', array('type' => 'task', 'id' => $this->id)); ?>" title="Timer" rel="facebox">
				<?php echo $this->InteractIcon('timer', 'Timer');?>
				<div class="action_text">Timer</div>
			</a>
		</div>		 
		<?php endif; ?>	
					
		<?php if($this->CheckPermission('manage_tasks')):?>
		<div class="actions">
			<a href="<?php echo $this->url('tasks/remove', array('task_id' => $this->id)); ?>" rel="facebox" title="Delete">
				<?php echo $this->InteractIcon('cross', 'Delete');?>
				<div class="action_text">Delete</div>
			</a>
		</div>		
		<div class="actions">
			<a href="<?php echo $this->url('tasks/edit', array('task_id' => $this->id)); ?>">
				<?php echo $this->InteractIcon('pencil', 'Edit');?>
				<div class="action_text">Edit</div>
			</a> 
		</div>
		<?php endif; ?>	
				
</div>
<script type="text/javascript">
jQuery(document).ready(function($){
	$("#task_progress_<?php echo $this->task['id']; ?>").progressBar();
});
</script>

<?php echo $this->Breadcrumb('task', $this->id); ?>
<?php 
$fail = FALSE;
if($this->task['duration'] > 0):
	if($this->hours['total'] > $this->task['duration']):
?>
	<div class="fail png_bg">
		This task is over the time estimate by <?php echo number_format(($this->hours['total']-$this->task['duration']), 2); ?> hours!
	</div>
<?php 
	endif;
endif; 

if(!in_array($this->task['status'], array('4','5','6')) && $this->IsDatePast($this->task['end_date'])):

	$task_end_date = new DateTime($this->task['end_date']);
	$now_date = new DateTime(date('Y-m-d H:i:s'));
	$interval = $task_end_date->diff($now_date);
?>
	<div class="fail png_bg">
		This task is <?php echo $interval->days; ?> days over due! Please update the end date or finish the task ASAP! 
	</div>
<?php 
endif;
?>

<div class="item_details">
    <div class="items">
    	<p>
			<span class="bold">Project:</span> <a href="<?php echo $this->url('projects/view', array('project_id' => $this->task['project_id'])); ?>"><?php echo $this->Truncate($this->task['project_name'], '25'); ?></a><br />
			<span class="bold">Status:</span> <?php echo $this->TaskStatus($this->task['status']); ?><br />
			<span class="bold">Priority:</span> <?php echo $this->TaskPriority($this->task['priority']); ?><br />
			<span class="bold">Type:</span> <?php echo $this->TaskType($this->task['type']); ?>    	
    	</p>
    </div>
    <div class="items">
    	<p>
			<span class="bold"><?php echo ($this->IsDatePast($this->task['start_date']) ? 'Started' : 'Starts'); ?>:</span> <?php echo $this->RelativeDate($this->task['start_date']); ?><br />
			<span class="bold"><?php echo ($this->IsDatePast($this->task['end_date']) ? 'Ended' : 'Ends'); ?>:</span> <?php echo $this->RelativeDate($this->task['end_date']); ?><br />   	
    	</p>
    </div>
	<?php 
	$assigned_data = array(
					'id' => $this->task['assigned_to'], 
					'first_name' => $this->task['assigned_first_name'], 
					'last_name' => $this->task['assigned_last_name']
	);
	?>    
    <div class="items" style="padding-left:10px;">
    	<p>			
			<span class="bold">Expected Duration:</span> <?php echo $this->task['duration']; ?> hours<br />
			<span class="bold">Assigned To:</span> <?php echo ($this->task['assigned_to'] == 0 ? 'Unassigned' : $this->MakeLink('user', $assigned_data)); ?><br />	
    		<span class="bold"></span> <span class="progressBar" id="task_progress_<?php echo $this->task['id']; ?>"><?php echo $this->task['progress']; ?>%</span>
    	</p>
    </div>
    
    <div class="items" style="padding-left:10px;">
		<?php 
			$options = array('hours' => $this->hours, 'type' => 'task', 'id' => $this->id);
			echo $this->partial('pm/times/partials/hour_status', $options); 		
		?>
    </div>    
</div>

<br clear="all" />

<?php if($this->assigned_to): ?>
<div class="task_updater png_bg">
	<div style="float:left">
		
	<div style="float:left">Update Progress: </div>
	<div id="current_value" style="float:left; padding-left:5px;"> <?php echo $this->task['progress']; ?>%</div> 
	</div>
	<br clear="all" />
	<div id="task_progress_slider" ></div>  

</div>

<script type="text/javascript" charset="utf-8">
var slide_int = null;
var task_thing = $("#task_updater");
var progress_obj = $("#task_progress_<?php echo $this->task['id']; ?>");
$(document).ready(function() {
	$( "#task_progress_slider" ).slider({ 
		min: 0,
		max: 100,
		range: "min",
		animate: true, 
		value: <?php echo $this->task['progress']; ?>,
		slide: function(event, ui){
			var mypos = ui.value;
			$('#current_value').css('left', mypos).text(ui.value+'%'); 
			progress_obj.text(mypos+'%');
		},
		change: function(event, ui){
			update_slider(ui.value);
		    $.ajax({ 
		    	type: "POST",
		    	data: "id=<?php echo $this->task['id']; ?>&progress="+ui.value,
			    url: "/api/task/update-progress/<?php echo $this->task['id']; ?>", 
			    context: document.body, 
			    success: function(){
				    $("#task_updater").css("color","red");
		   		 }}
	   		);
		}			
	});

	function update_slider(value){
	    $('#current_value').text(value+'%');
	    progress_obj.text(value+'%');
	    progress_obj.progressBar();
	}	
});
</script>
<?php endif; ?>
<?php if($this->task['description']): ?>
<h2>Description:</h2>
<p><?php echo $this->FormatHtml($this->task['description']); ?></p>
<?php endif; ?>

<div class="content_headers">
	<div class="assignment_history_header">Assignment History</div>	
</div>
<?php 
if($this->assignment_history):
	$options = array('assignment_history' => $this->assignment_history);
	echo $this->partial('pm/tasks/partials/assignments', $options); 
else: 
?>
<div class="information png_bg">This task hasn't been assigned to anyone.</div>
<?php 
endif;
?>

<?php if($this->CheckPermission('view_files')): ?>
	<div class="content_headers">
		<div class="file_header">Files</div>		
		<div class="actions">
			<a href="<?php echo $this->url('files/all', array('type'=>'task', 'id' => $this->id)); ?>" title="View All">
				<?php echo $this->InteractIcon('view-all', 'View All');?>
				<div class="action_text">View All</div>
			</a>
		</div>	
		
		<?php if($this->CheckPermission('manage_files')): ?>	
		<div class="actions">
			<a href="<?php echo $this->url('files/add', array('type'=>'task', 'id' => $this->id)); ?>" rel="facebox" title="Add File">
				<?php echo $this->InteractIcon('add', 'Add');?> 
				<div class="action_text">Add File</div>
			</a>
		</div>
		<?php endif; ?>
	</div>
	<?php 
	if($this->files):
		$options = array('files' => $this->files, 'facebox' => 'yes');
		echo $this->partial('pm/files/partials/files', $options); 
	else: 
	?>
	<div class="information png_bg">There aren't any files uploaded yet. Want to <a href="<?php echo $this->url('files/add', array('type'=>'task', 'id' => $this->id)); ?>" rel="facebox">add</a> one?</div>
	<?php 
	endif;
endif;
?>

<div class="content_headers">
	<div class="note_header">Notes</div>		
	<div class="actions">
		<a href="<?php echo $this->url('notes/all', array('type' => 'task', 'id' => $this->id)); ?>" title="View All">
			<?php echo $this->InteractIcon('view-all', 'View All');?> 
			<div class="action_text">View All</div>
		</a>
	</div>	
	<div class="actions">
		<a rel="facebox" href="<?php echo $this->url('notes/add', array('type' => 'task', 'id' => $this->id)); ?>" title="Add Note">
			<?php echo $this->InteractIcon('add', 'Add');?>  
			<div class="action_text">Add Note</div>
		</a>
	</div>
</div>
<?php 
if($this->notes):
	$options = array('notes' => $this->notes, 'facebox' => 'yes');
	echo $this->partial('pm/notes/partials/notes', $options); 
else: 
?>
<div class="information png_bg">There aren't any notes added yet. Want to <a href="<?php echo $this->url('notes/add', array('type'=>'task', 'id' => $this->id)); ?>" rel="facebox">add</a> one?</div>
<?php 
endif;
?>

<div class="content_headers">
	<div class="bookmark_header">Bookmarks</div>	
	<div class="actions">
		<a href="<?php echo $this->url('bookmarks/all', array('type' => 'task', 'id' => $this->id), null, TRUE); ?>" title="View All">
			<?php echo $this->InteractIcon('view-all', 'View All');?>
			<div class="action_text">View All</div>
		</a>
	</div>	
	<div class="actions">
		<a rel="facebox" href="<?php echo $this->url('bookmarks/add', array('type' => 'task', 'id' => $this->id)); ?>" title="Add Bookmark">
			<?php echo $this->InteractIcon('add', 'Add');?>  
			<div class="action_text">Add Bookmark</div>
		</a>
	</div>
</div>
<?php 
if($this->bookmarks):
	$options = array('bookmarks' => $this->bookmarks, 'facebox' => 'yes');
	echo $this->partial('pm/bookmarks/partials/bookmarks', $options); 
else: 
?>
<div class="information png_bg">There aren't any bookmarks added yet. Want to <a href="<?php echo $this->url('bookmarks/add', array('type' => 'task', 'id' => $this->id)); ?>" rel="facebox">add</a> one?</div>
<?php 
endif;
?>

<?php if($this->CheckPermission('view_time')): ?>
	<div class="content_headers">
		<div class="timetracker_header">Timetracker</div>			
		<div class="actions">
			<a href="<?php echo $this->url('times/view', array('type' => 'task', 'id' => $this->id)); ?>" title="View All">
				<?php echo $this->InteractIcon('view-all', 'View All');?>
				<div class="action_text">View All</div>
			</a>
		</div>
	</div>
	<?php 
	if($this->times): 
		$options = array('times' => $this->times, 'enable_date' => 'yes');
		echo $this->partial('pm/times/partials/times', $options); 
	else: 
	?>
	<div class="information png_bg">There aren't any times added yet. </div>
	<?php 
	endif;
endif;
?>
