<?php $this->headTitle()->append( $this->_('storage_bp_settings_menu', 'sites') )->append( $this->_('sites', 'sites') ); ?>
<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('storage_bp_settings_menu', 'sites'); ?> <small><?php echo $this->layout()->site_data['site_name']; ?></small></h1>
    </div>
      <div class="row">
        <div class="col-sm-3 col-md-3 sidebar">
            <?php echo $this->render('sites/global/_sidebar'); ?>
      </div>
      <div class="col-sm-9 col-md-9">
      <?php echo $this->render('sites/global/_errors', array('site_data' => $this->layout()->site_data)); ?> 
      <?php echo $this->render('sites/settings/partials/_tabs', array('active_tab' => $this->section, 'site_data' => $this->layout()->site_data)); ?>
      <?php echo $this->render('partials/_add_menu', array('available_storage_drivers' => $available_storage_drivers, 'site_data' => $this->layout()->site_data)); ?>
      <?php //echo $this->render('partials/_tabs'); ?>  
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th><?php echo $this->_('id', 'app'); ?></th>
                    <th><?php echo $this->_('site_name', 'sites'); ?></th>
                    <th><?php echo $this->_('platform', 'sites'); ?></th>
                    <th><?php echo $this->_('created_date', 'app'); ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($storage_locations AS $storage):?>
                <tr class="<?php echo ($site['errors'] != '' ? 'warning' : ''); ?>">
                    <td><?php echo $site['id']; ?></td>
                    <td><?php echo $site['site_name']; ?></td>
                    <td><?php echo $site['platform']; ?></td>
                    <td><?php echo $this->FormatDate($site['created_date']); ?></td>
                    <td>
                        <div class="dropdown pull-right">
                          <button class="btn btn-default dropdown-toggle" style="height:12px;" type="button" id="dropdownMenu<?php echo $user['id']; ?>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            
                            <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu" aria-labelledby="dropdownMenu<?php echo $this->layout()->site_data['id']; ?>">
                            <li><a href="<?php echo $this->url('sites/edit', array('site_id' => $this->layout()->site_data['id'])); ?>"><?php echo $this->glyphicon('pencil'); ?> <?php echo $this->_('edit_site', 'sites'); ?></a></li>
                            <li><a href="<?php echo $this->url('sites/view', array('site_id' => $this->layout()->site_data['id'])); ?>"><?php echo $this->glyphicon('eye-open'); ?> <?php echo $this->_('view_site', 'sites'); ?></a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="<?php echo $this->url('sites/remove', array('site_id' => $this->layout()->site_data['id'])); ?>"><?php echo $this->glyphicon('remove'); ?> <?php echo $this->_('remove_site', 'sites'); ?></a></li>
                          </ul>
                        </div>                
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>      
        <?php echo $this->Pagination('manage_sites', $this->total_pages, $this->page); ?>        

              
      </div>

    </div>
</div>    