<?php $this->headTitle()->append( $this->_('storage_bp_settings_menu', 'sites') )->append( $this->_('sites', 'sites') ); ?>
<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('storage_bp_settings_menu', 'sites'); ?> <small><?php echo $this->layout()->site_data['site_name']; ?></small></h1>
    </div>
      <div class="row">
        <div class="col-sm-3 col-md-3 sidebar">
            <?php echo $this->render('sites/global/_sidebar'); ?>
      </div>
      <div class="col-sm-9 col-md-9">
      <?php echo $this->render('sites/global/_errors', array('site_data' => $this->layout()->site_data)); ?> 
      <?php echo $this->render('sites/settings/partials/_tabs', array('active_tab' => $this->section, 'site_data' => $this->layout()->site_data)); ?>
      <?php echo $this->render('partials/_add_menu', array('available_storage_drivers' => $available_storage_drivers, 'site_data' => $this->layout()->site_data)); ?>
      <?php //echo $this->render('partials/_tabs'); ?>  
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th><?php echo $this->_('storage_location_name', 'sites'); ?></th>
                    <th><?php echo $this->_('type', 'sites'); ?></th>
                    <th><?php echo $this->_('status', 'sites'); ?></th>
                    <th><?php echo $this->_('created_date', 'sites'); ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($storage_locations AS $storage): ?>
                <tr class="">
                    <td><a href="<?php echo $this->url('site_storage/edit', array('site_id' => $this->layout()->site_data['id'], 'storage_id' => $storage['storage_location_id'])); ?>"><?php echo $storage['storage_location_name']; ?></a></td>
                    <td><img src="<?php echo $bp_static_path.'/images/storage/'.$this->escapehtmlattr($storage['storage_location_driver']); ?>.png" /></td>
                    <td><?php if ($storage['storage_location_status'] == '1'):?>Active<?php else: ?>Inactive<?php endif;?></td>
                    <td><?php echo $this->m62DateTime($storage['storage_location_create_date']); ?></td>
                    <td>
            			<?php if($can_remove): ?>
            			<a href="<?php echo $this->url('site_storage/remove', array('site_id' => $this->layout()->site_data['id'], 'storage_id' => $storage['storage_location_id'])); ?>" class="delete icon" title="Delete" role="button">Delete</a>
            			<?php endif; ?>                    
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>      
        <?php echo $this->Pagination('manage_sites', $this->total_pages, $this->page); ?>        

              
      </div>

    </div>
</div>    