<?php $this->headTitle()->append( $this->_('storage_bp_settings_menu', 'sites') )->append( $this->_('sites', 'sites') ); ?>
<div class="container">
    <div class="page-header">
    	<h1><?php echo $this->_('storage_bp_settings_menu', 'sites'); ?> <small><?php echo $this->layout()->site_data['site_name']; ?></small></h1>
    </div>
      <div class="row">
        <div class="col-sm-3 col-md-3 sidebar">
            <?php echo $this->render('sites/global/_sidebar'); ?>
      </div>
      <div class="col-sm-9 col-md-9">
      <?php echo $this->render('sites/global/_errors', array('site_data' => $this->layout()->site_data)); ?> 
      <?php echo $this->render('sites/settings/partials/_tabs', array('active_tab' => $this->section, 'site_data' => $this->layout()->site_data)); ?>
      <?php echo $this->render('partials/_add_menu', array('available_storage_drivers' => $available_storage_drivers, 'site_data' => $this->layout()->site_data)); ?>

      <h2><?php echo $this->_('delete_storage_confirm', 'sites'); ?></h2>
      <p><?php echo $storage_location['storage_location_name']; ?></p> 
      
            <?php 
            $form = $this->form;
            $form->setAttribute('id', 'site_form');
            $form->prepare();
            echo $this->form()->openTag($form);
            $csrf = $form->get('_x');
            echo $this->formRow($csrf);
            
            $url = $this->url('sites/view', array('site_id' => $site_data['id']));
            echo sprintf($this->_('action_can_not_be_undone', 'sites'), $site_data['site_name'], $url);
            ?>
            
            <br clear="all" /><br clear="all" />
            <input type="submit" class="btn btn-primary" value="<?php echo $this->_('remove_storage_location', 'sites'); ?>" />
            <?php echo $this->form()->closeTag() ?>       

              
      </div>

    </div>
</div>    