<?php 
$form = $this->form;
$form->setAttribute('id', 'invoices_form');
$form->setAttribute('action', $form_action);
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);

	if($this->id > 0)
		echo '<input type="hidden" value="'.$this->id.'" name="id" />';
?>
<div id="form_tabs">
	<ul>

		<li><a href="#general">General</a></li>
		<li><a href="#times">Times</a></li>
		<li><a href="#line_items">Line Items</a></li>
	</ul>
	<div id="general">

		<p>
			<label for="invoice_number">Invoice Number</label>
			<?php $name = $form->get('invoice_number'); echo $this->formRow($name); ?>
		</p>
		<p>
			<label for="status">Status</label>
			<?php $name = $form->get('status'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="date">Date of Issue</label>
			<?php $name = $form->get('date'); echo $this->formRow($name); ?>
		</p>
		<p>
			<label for="po_number">PO Number</label>
			<?php $name = $form->get('po_number'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="discount">Discount</label>
			<?php $name = $form->get('discount'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="override_total">Override Total* </label>
			<?php $name = $form->get('override_total'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="notes">Note</label>
			<?php $name = $form->get('notes'); echo $this->formRow($name); ?>
		</p>
		
		<p>
			<label for="description">Description</label>
			<?php $name = $form->get('terms_conditions'); echo $this->formRow($name); ?>
		</p>		
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>
		
		<p><small>*(if set, total from lined items and times are ignored)</small></p>
		
	</div>
	<div id="times">
	
		<?php 
		$options = array(
			'times' => $this->time_data, 
			'enable_checkbox' => true, 
			'enable_date' => true, 
			'enable_project' => true, 
			'field_name' => 'invoice_time',
			'tableid' => 'moji_invoice_times',
			'hide_desc' => true,
			'enable_hour_rate_field' => true,
			'hour_rate_field_value' => $this->company_data['default_hourly_rate'],
			'company_data' => $this->company_data
		);
		echo $this->partial('pm/times/partials/times', $options);
		?>	
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>
	
	</div>
	<div id="line_items">
	
		<?php 
		$options = array(
			'times' => $this->time_data, 
			'enable_checkbox' => true, 
			'enable_date' => true, 
			'enable_project' => true, 
			'field_name' => 'invoice_time',
			'tableid' => 'moji_invoice_line_items',
			'hide_desc' => true,
			'enable_hour_rate_field' => true,
			'hour_rate_field_value' => $this->company_data['default_hourly_rate'],
			'company_data' => $this->company_data
		);
		echo $this->partial('pm/invoices/partials/line-items', $options);
		?>	
	
	</div>
	
</div>			
<?php echo $this->ConfirmPageUnload('#invoice_form')?>
<?php echo $this->form()->closeTag() ?>


<script type="text/javascript">
$.validator.setDefaults({
	//submitHandler: function() { alert("submitted!"); }
});

$().ready(function() {

	$("#invoices_form").validate({
		rules: {
			invoice_number: "required",
			date: "required"
		},
		messages: {
			invoice_number: "Please enter an invoice number",
			date: "Please select a date"
		}
	});

});

</script>