<table cellpadding="0" cellspacing="0" class="<?php echo ($this->tableclass) ? $this->tableclass : 'tablesorter'; ?>" id="<?php echo ($this->tableid) ? $this->tableid : 'moji_invoices'; ?>">
	<thead>
		<tr>
			<th>Invoice #</th>
			<th>Date Sent</th>
			<th>Status</th>
			<th>Amount</th>
			<th>Last Modified</th>
			<?php if($this->enable_actions):?>
			<th>Actions</th>
			<?php endif; ?>
		</tr>
	</thead>

	<tbody>
		<?php 
		$i = 0;
		foreach($this->invoices as $invoice)
		{
		?>
		<tr>
			<td><a title="<?php echo $invoice['invoice_number']; ?>" href="<?php echo $this->url('invoices/view', array('invoice_id' => $invoice['id'])); ?>"><?php echo $invoice['invoice_number']; ?></a></td>
			<td><?php echo $this->RelativeDate($invoice['date']); ?></td>
			<td><?php echo $invoice['status']; ?></td>
			<td><?php echo $this->currencyFormat($invoice['amount'], $this->company_data['currency_code'], $this->company_data['client_language']) ?></td>
			<td><?php echo $this->RelativeDate($invoice['last_modified']); ?></td>
			<?php if($this->enable_actions):?>
			<td>
			<a href="<?php echo $this->url('contacts/edit', array('contact_id' => $contact['id'])); ?>" title="Edit"><?php echo $this->InteractIcon('pencil', 'Edit');?></a>
			<a <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?> href="<?php echo $this->url('contacts/remove', array('contact_id' => $contact['id'])); ?>" title="Delete"><?php echo $this->InteractIcon('cross', 'Delete');?></a>
			</td>
			<?php endif; ?>
		</tr>
		<?php 
		}
		?>
	</tbody>
</table>