<table cellpadding="0" cellspacing="0" class="<?php echo ($this->tableclass) ? $this->tableclass : 'tablesorter'; ?>" id="<?php echo ($this->tableid) ? $this->tableid : 'moji_times'; ?>">
	<thead>
		<tr>
			<th></th>
			<th>Item</th>
			<th>Description</th>
			<th>Unit Cost</th>
			<th>Qty</th>
		</tr>
	</thead>

	<tbody>
	<?php for($i=0; $i<=9; $i++): ?>
		<tr>
			<td>#<!-- <?php echo '0'.$i; ?> --><?php echo $i+1; ?></td>
			<td nowrap><input type="text" name="line_item[<?php echo $i; ?>][item]" value="" size="25" /></td>
			<td><input type="text" name="line_item[<?php echo $i; ?>][description]" value="" size="25" /></td>
			<td nowrap>$<input type="text" name="line_item[<?php echo $i; ?>][unit_cost]" value="" size="4" /></td>
			<td nowrap><input type="text" name="line_item[<?php echo $i; ?>][qty]" value="1" size="4" /></td>
		</tr>
	<?php endfor; ?>
	</tbody>
</table>

<script>
$(document).ready(function() {

	var t = $('#moji_invoice_line_items').dataTable({
		"bJQueryUI": true,
		"bStateSave": false,
        "bLengthChange": false,
        "bPaginate": false,
		"aaSorting": [[ 0, "asc" ]]
	}); 	
} );
</script>