<div class="content_headers" style="padding-top:0px;">
	<div class="company_header">Edit Company</div>		
</div>
<div class="back_link_content">
	<a href="<?php echo $this->url('companies/view', array('company_id'=>$this->company_data['id']), null, TRUE); ?>" title="Back to <?php echo $this->company_data['name']; ?>">
		Back to <?php echo $this->company_data['name']; ?>	
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to '.$this->company_data['name']);?></div>
</div>
<br clear="all" />
<?php 
$options = array('form' => $this->form, 'id' => $this->id, 'company' => $this->company_data);
echo $this->partial('pm/companies/partials/form', $options); 
?>