<div class="content_headers" style="padding-top:0px;">

	<div class="company_header">
	<?php if($this->company_filter || $this->company_filter !== FALSE): ?>
	<?php echo $this->CompanyType($this->company_filter); ?>
	<?php endif; ?>
	Companies
	
	</div>
		
		<?php 
		if($this->CheckPermission('manage_companies')):
			echo $this->ActionBlock('add', 'Add Company', $this->url('companies/add'));
		endif; 
		?>
		<br clear="all" />		
</div>

<?php 
if($this->companies):
?>
<table cellpadding="0" cellspacing="0" class="<?php echo ($this->tableclass) ? $this->tableclass : 'tablesorter'; ?>" id="<?php echo ($this->tableid) ? $this->tableid : 'moji_companies'; ?>">
	<thead>
		<tr>
			<th>Company Name</th>
			<th>Phone</th>
			<th>Type</th>
			<th>Added</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<?php 
		$i = 0;
		foreach($this->companies as $company)
		{
		?>
		<tr>
			<td><a title="<?php echo $company['name']; ?>" href="<?php echo $this->url('companies/view', array('company_id'=> $company['id'])); ?>"><?php echo $company['name']; ?></a></td>
			<td>
			<?php 
			if($company['phone1'])
			{
				echo $company['phone1']; 
			}
			elseif($company['phone2'])
			{
				echo $company['phone2'];
			}
			else
			{
				echo 'N/A';
			}
			?>
			</td>
			<td><?php echo $this->companyType($company['type']); ?></td>
			<td><?php echo $this->RelativeDate($company['created_date']); ?></td>
			<td>
			<?php if($this->CheckPermission('view_files')):?>
				<a href="<?php echo $this->url('files/all', array('type' => 'company', 'id' => $company['id'])); ?>" title="Files"><?php echo $this->InteractIcon('folder', 'View Company Files');?></a>
			<?php endif; ?>
			
			<?php if($this->CheckPermission('view_company_contacts')):?>				
				<a href="<?php echo $this->url('contacts/all', array('company_id'=>$company['id'])); ?>" title="Contacts"><?php echo $this->InteractIcon('user', 'View Company Users');?></a>
			<?php endif; ?>
			
			<?php if($this->CheckPermission('manage_companies')):?>
				<a href="<?php echo $this->url('companies/edit', array('company_id' => $company['id'])); ?>" title="Edit"><?php echo $this->InteractIcon('pencil', 'Edit Company');?></a>
				<a href="<?php echo $this->url('companies/remove', array('company_id' => $company['id'])); ?>" title="Delete" rel="facebox"><?php echo $this->InteractIcon('cross', 'Delete Company');?></a>
			<?php endif; ?>
			</td>
		</tr>
		<?php 
		}
		?>
	</tbody>
</table>

<?php else: ?>

<div class="information png_bg">There aren't any 
	<?php if($this->company_filter): ?>
	<?php echo strtolower($this->CompanyType($this->company_filter)); ?>
	<?php endif; ?>
	companies
	
 setup. <?php if($this->CheckPermission('manage_companies')):?>Want to <a href="<?php echo $this->url('companies/add', array('module' => 'pm','controller' => 'companies','action'=>'add'), null, TRUE); ?>">add</a> one?<?php endif; ?></div>

<?php endif; ?>