<div class="content_headers" style="padding-top:0px;">
	<div class="company_header">Remove Company: <?php echo $this->company_data['name']?></div>		
</div>
<div class="attention png_bg">
Are you sure you want to remove "<?php echo $this->company_data['name']?>"? This can not be undone...
</div>

<?php 
$form = $this->form;
$form->setAttribute('id', 'remove_company_form');
$form->setAttribute('action', $this->url('companies/remove', array('company_id' => $this->company_data['id'])));
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
	<?php $field = $form->get('confirm'); echo $this->formRow($field); ?> <?php $field = $form->get('fail'); echo $this->formRow($field); ?>
<?php echo $this->form()->closeTag() ?>

<h2>Company Details</h2>
<p>
"<a href="<?php echo $this->url('companies/view', array('company_id' => $this->company_data['id'])); ?>"><?php echo $this->company_data['name']?></a>" contains:
<br />
<?php echo $this->project_count; ?> Projects<br />
<?php echo $this->task_count; ?> Tasks<br />
<?php echo $this->file_count; ?> Files

</p>