<?php 
$form = $this->form;
$form->setAttribute('id', 'option_form');
$form->setAttribute('action', $this->form_action);
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
<?php 
if($this->id > 0)
	echo '<input type="hidden" value="'.$this->id.'" name="id" />';
?>
	
		<p>
			<label for="name">Title</label>
			<?php $field = $form->get('name'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="area">Area</label>
			<?php $field = $form->get('area'); echo $this->formRow($field); ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>			

<?php echo $this->ConfirmPageUnload('#option_form')?>
<?php echo $this->form()->closeTag() ?>