<table cellpadding="0" cellspacing="0" class="<?php echo ($this->tableclass) ? $this->tableclass : 'tablesorter'; ?>" id="<?php echo ($this->tableid) ? $this->tableid : 'moji_ips'; ?>">
	<thead>
		<tr>
			<th>Name</th>
			<th>Area</th>	
			<th>Created</th>
			<th>Modified</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<?php 
		$i = 0;
		foreach($this->options as $option)
		{
		?>
		<tr>
			<td>
			<a title="<?php echo $option['name']; ?>" href="<?php echo $this->url('options/view', array('option_id'=> $option['id'])); ?>" <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?>><?php echo $option['name']; ?></a>
			</td>
			<td><?php 
			echo ucwords(str_replace('_', ' ', $option['area'])); ?></td>
			<td><?php echo $this->RelativeDate($option['created_date']); ?></td>
			<td><?php echo $this->RelativeDate($option['last_modified']); ?></td>
			
			<td>
				<a href="<?php echo $this->url('options/edit', array('option_id'=> $option['id'])); ?>" <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?> title="Edit"><?php echo $this->InteractIcon('pencil', 'Edit');?></a>
				<a href="<?php echo $this->url('options/remove', array('option_id'=> $option['id'])); ?>" <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?> title="Delete"><?php echo $this->InteractIcon('cross', 'Delete');?></a>
			</td>
		</tr>
		<?php 
		}
		?>
	</tbody>
</table>