<div class="content_headers" style="padding-top:0px;">
	<div class="admin_header">Edit Type Option</div>			
</div>
<?php if(!$this->ajax_mode): ?>
<div class="back_link_content">
	<a href="<?php echo $this->url('options/view', array('option_id' => $this->id)); ?>" title="Back to Option">
		Back to Option
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to Options');?></div>
</div>	
<br clear="all" />
<?php endif; ?>
<?php 
$options = array('form' => $this->form, 'id' => $this->id, 'form_action' => $this->form_action);
echo $this->partial('pm/options/partials/form', $options); 
?>