<div class="content_headers" style="padding-top:0px;">
	<div class="admin_header">Type Options</div>	
		<div class="actions">
			<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'options', 'page' => 'main'), null, TRUE); ?>" rel="facebox" title="Add Project">
				<?php echo $this->InteractIcon('help', 'About Type Options');?>
				<div class="action_text">Help</div>
			</a>
		</div>	
		<div class="actions">
			<a href="<?php echo $this->url('options/add', array('module' => 'pm','controller' => 'options','action'=>'add'), null, FALSE); ?>" title="Add Ip Address" rel="facebox">
				<?php echo $this->InteractIcon('add', 'Add Project');?>
				<div class="action_text">Add Option</div>
			</a>
		</div>
</div>



<?php 
if($this->options):

	$options = array('options' => $this->options, 'enable_actions' => 'yes', 'facebox' => 'yes');
	echo $this->partial('pm/options/partials/options', $options); 

else: 
?>

<div class="information png_bg">There aren't any options setup yet. Want to <a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'options','action'=>'add'), null, TRUE); ?>" rel="facebox">add</a> one?.</div>

<?php 
endif; ?>