<div class="content_headers" style="padding-top:0px;">
	<div class="admin_header">Remove Option</div>	
</div>
<?php if(!$this->ajax_mode): ?>
<div class="back_link_content">
	<a href="<?php echo $this->url('options/view', array('option_id'=>$this->id)); ?>" title="Back to Option">
		Back to Option
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to Option');?></div>
</div>	
<br clear="all" />
<?php endif; ?>

<div class="attention png_bg">
Are you sure you want to remove the Option "<?php echo $this->option['name']?>"? This can not be undone...
</div>
<p>
<?php 
$form = $this->form;
$form->setAttribute('id', 'ip_form');
$form->setAttribute('action', $this->url('options/remove', array('option_id' => $this->option['id'])));
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
	<?php $field = $form->get('confirm'); echo $this->formRow($field); ?> <?php $field = $form->get('fail'); echo $this->formRow($field); ?>
<?php echo $this->form()->closeTag() ?>
</p>
