<div class="content_headers" style="padding-top:0px;">

	<div class="admin_header">Viewing Option: <?php echo $this->option_info['name']; ?></div>
		
		<div class="actions">
			<a rel="facebox" href="<?php echo $this->url('options/remove', array('option_id' => $this->id)); ?>" title="Delete">
				<?php echo $this->InteractIcon('cross', 'Delete');?>
				<div class="action_text">Delete</div>
			</a>
		</div>		
		<div class="actions">
			<a href="<?php echo $this->url('options/edit', array('option_id' => $this->id)); ?>" title="Edit">
				<?php echo $this->InteractIcon('pencil', 'Edit');?>
				<div class="action_text">Edit</div>
			</a> 
		</div>
</div>
<?php if(!$this->ajax_mode): ?>
<div class="back_link_content">
	<a href="<?php echo $this->url('options'); ?>" title="Back to Options">
		Back to Options
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to Options');?></div>
</div>	
<br clear="all" />
<?php endif; ?>
<div class="item_details">
    <div class="items" style="padding-left:10px;">
    	<p>
			<span class="bold">Modified:</span> <?php echo $this->RelativeDate($this->option_info['last_modified']); ?><br />
			<span class="bold">Created:</span> <?php echo $this->RelativeDate($this->option_info['created_date']); ?> 
    	</p>
    </div> 
</div>
