Hello <?php echo $user_data['first_name']; ?>, <br /><br />

To confirm your IP please click the below URL: <br /><br />

<?php echo $this->ServerUrl($this->url('ips/verify-allow', array('verify_code' => $verify_code))); ?><br /><br />

Copy and paste the URL in a new browser window if you can't click on it.<br /><br />

Please keep in mind that the link will only work for 24 hours; after that it will be inactive.<br /><br />

<?php echo $this->_('sent_by_moji', 'pm'); ?>