<div class="content_headers" style="padding-top:0px;">

	<div class="bookmark_header">
	<?php if($this->company): ?>
		Company Bookmarks For: <?php echo $this->company['name']; ?>
	<?php elseif($this->project): ?>
		Project Bookmarks For: <?php echo $this->project['name']; ?>
	<?php elseif($this->task): ?>
		Task Bookmarks For: <?php echo $this->task['name']; ?>		
	<?php else: ?>
		Bookmarks
	<?php endif; ?>
	</div>
	
	<div class="actions">
		<a href="<?php echo $this->url('bookmarks/add', array('type'=> $this->type,'id'=> $this->id)); ?>" rel="facebox" title="Add Bookmark">
			<?php echo $this->InteractIcon('add', 'Add Bookmark');?>
			<div class="action_text">Add Bookmark</div>
		</a> 
	</div>
</div>

<?php 
$options = array('company' => $this->company, 'project' => $this->project, 'task' => $this->task);
echo $this->BackToLink($options); 

if($this->bookmarks):

	$options = array('bookmarks' => $this->bookmarks, 'enable_actions' => 'yes', 'facebox' => 'yes');
	echo $this->partial('pm/bookmarks/partials/bookmarks', $options);

else: ?>

<div class="information png_bg">There aren't any bookmarks added yet. Want to <a href="<?php echo $this->url('bookmarks/add', array('type'=> $this->type,'id'=> $this->id)); ?>" rel="facebox">add</a> one?.</div>

<?php endif; ?>