<div class="content_headers" style="padding-top:0px;">
	<div class="note_header">Remove Bookmark: <?php echo $this->bookmark['name']?></div>		
</div>
<div class="attention png_bg">
Are you sure you want to remove "<?php echo $this->bookmark['name']?>"? This can not be undone...
</div>

<p>
<?php 
$form = $this->form;
$form->setAttribute('id', 'bookmark_form');
$form->setAttribute('action', $this->url('bookmarks/remove', array('bookmark_id' => $this->id)));
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
	<?php $field = $form->get('confirm'); echo $this->formRow($field); ?> <?php $field = $form->get('fail'); echo $this->formRow($field); ?>
<?php echo $this->form()->closeTag() ?>
</p>