<div class="content_headers" style="padding-top:0px;">

	<div class="bookmark_header"><?php echo $this->bookmark['name']; ?></div>
		
		<div class="actions">
			<a rel="facebox" href="<?php echo $this->url('bookmarks/remove', array('bookmark_id' => $this->bookmark['id'])); ?>" title="Delete">
				<?php echo $this->InteractIcon('cross', 'Remove Bookmark');?>
				<div class="action_text">Delete</div>
			</a>
		</div>		
		<div class="actions">
			<a href="<?php echo $this->url('bookmarks/edit', array('bookmark_id' => $this->bookmark['id'])); ?>" title="Edit">
				<?php echo $this->InteractIcon('pencil', 'Edit Bookmark');?>
				<div class="action_text">Edit</div>
			</a> 
		</div>
</div>
<?php 
$owner_data = array(
				'id' => $this->bookmark['owner'], 
				'first_name' => $this->bookmark['owner_first_name'], 
				'last_name' => $this->bookmark['owner_last_name']
);
?>
<div class="item_details">
    <div class="items" style="padding-left:10px;">
    	<p>
			<span class="bold">Last Modified:</span> <?php echo $this->RelativeDate($this->bookmark['last_modified']); ?><br />
			<span class="bold">Created Date:</span> <?php echo $this->RelativeDate($this->bookmark['created_date']); ?> 
    	</p>
    </div>
    <div class="items" style="padding-left:10px;">
    	<p>
			<span class="bold">Company:</span> <a href="<?php echo $this->url('companies/view', array('company_id' => $this->bookmark['company_id'])); ?>"><?php echo $this->bookmark['company_name']; ?></a><br />
			<?php if($this->bookmark['project_name']): ?>
			<span class="bold">Project:</span> <a href="<?php echo $this->url('projects/view', array('project_id' => $this->bookmark['project_id'])); ?>"><?php echo $this->bookmark['project_name']; ?></a><br />
			<?php endif; ?>
			<?php if($this->bookmark['task_name']): ?>
				<span class="bold">Task:</span> <a href="<?php echo $this->url('tasks/view', array('task_id' => $this->bookmark['task_id'])); ?>"><?php echo $this->bookmark['task_name']; ?></a>
			<?php endif; ?> 	
    	</p>
    </div>
</div>

<br clear="all" />

<h2>URL:</h2>
<p>
<a href="<?php echo $this->bookmark['url']; ?>" target="_blank"><?php echo $this->bookmark['url']; ?></a>
</p>

<?php if($this->bookmark['description']): ?>
<h2>Description:</h2>
<p>
<?php echo $this->FormatHtml($this->bookmark['description']); ?>    	
</p>
<?php endif; ?>
