<?php 
if($site_data['errors'] != '') :
    $errors = json_decode($site_data['errors']); 
    if($errors):
        foreach($errors AS $key => $error) :
?>
<div class="alert alert-warning" role="alert">
	<?php 
	
	if( $key == 'db_backup_past_expectation' || $key == 'file_backup_past_expectation' )
	{
	    if( $key == 'db_backup_past_expectation' )
	    {
	        $lang = sprintf(
	            $error,
	            $this->m62RelativeDateTime($this->layout()->backup_meta['database']['newest_backup_taken_raw']),
	            $this->url('backup', array('type' => 'database', 'site_id' => $site_data['id']))
	        );
	    }
	    else if ( $key == 'file_backup_past_expectation' )
	    {
	        $lang = sprintf(
	            $error,
	            $this->m62RelativeDateTime($this->layout()->backup_meta['files']['newest_backup_taken_raw']),
	            $this->url('backup', array('type' => 'files', 'site_id' => $site_data['id']))
	        );
	    }
	    echo $lang;
	}
	else{

	    echo $error;
	}
	
	if( $key == 'no_storage_locations_setup' )
	{
	    echo ' <a href="'.$this->url('site_settings', array('site_id' => $site_data['id'], 'section' => 'storage')).'">'.$this->_('setup_storage_location', 'sites').'</a>';
	}
	elseif( $key == 'license_number' )
	{
	    echo ' <a href="'.$context->url('/dashboard/backup_pro/settings/license').'">'.$view_helper->m62Lang('enter_license').'</a> or <a href="https://mithra62.com/projects/view/backup-pro">'.$this->_('purchase_a_license', 'sites').'</a>';
	}
	elseif( $key == 'invalid_working_directory' )
	{
	    echo ' <a href="'.$this->url('site_settings', array('site_id' => $site_data['id'], 'section' => 'general')).'">'.$this->_('check_working_dir', 'sites').'</a>';
	}
	elseif( $_error == 'no_db_backups_exist_yet' )
	{
	    echo ' <a href="'.$context->url('/dashboard/backup_pro/backup_database').'">'.$view_helper->m62Lang('would_you_like_to_backup_database_now').'</a>';
	}
	elseif( $_error == 'no_file_backups_exist_yet' )
	{
	    echo ' <a href="'.$context->url('/dashboard/backup_pro/backup_files').'">'.$view_helper->m62Lang('would_you_like_to_backup_files_now').'</a>';
	}
	elseif( $key == 'no_backup_file_location' )
	{
	    echo ' <a href="'.$this->url('site_settings', array('site_id' => $site_data['id'], 'section' => 'files')).'">Set File Backup Locations</a>';
	}
	?>
</div>
<?php 
        endforeach;
    endif;
endif;
?>  