<p>
	<span class="bold">Total Hours:</span> 
	<?php if($this->hours['total']): ?>
	<a href="<?php echo $this->url('times/view', array('type' => $this->type, 'id' => $this->id)); ?>">
	<?php endif; ?>
	<?php echo number_format($this->hours['total'], 2); ?>
	<?php if($this->hours['total']): ?>
	</a>
	<?php endif; ?>
	<br />
	
	<span class="bold">Paid Hours:</span> 
	<?php if($this->hours['paid']): ?>
	<a href="<?php echo $this->url('times/view', array('type' => $this->type, 'id' => $this->id, 'status' => 'paid')); ?>">
	<?php endif; ?>			
	<?php echo number_format($this->hours['paid'], 2); ?> 
	<?php if($this->hours['paid']): ?>
	</a>
	<?php endif; ?>			
	<br />
	
	<span class="bold">Unpaid Hours:</span> 
	<?php if($this->hours['unsent']): ?>
	<a href="<?php echo $this->url('times/view', array('type' => $this->type, 'id' => $this->id, 'status' => 'unsent'), null, TRUE); ?>">
	<?php endif; ?>				
	<?php echo number_format($this->hours['unsent'], 2); ?>
	<?php if($this->hours['unsent']): ?>
	</a>
	<?php endif; ?>			
	<br />
	
	<span class="bold">Pending Hours:</span> 
	<?php if($this->hours['sent']): ?>
	<a href="<?php echo $this->url('times/view', array('type' => $this->type, 'id' => $this->id, 'status' => 'sent')); ?>">
	<?php endif; ?>				
	<?php echo number_format($this->hours['sent'], 2); ?> 
	<?php if($this->hours['sent']): ?>
	</a>
	<?php endif; ?>			    	
</p>