<style>
#loading
{
	display:none;
}
</style>

<form action="<?php echo $this->escape($this->form->getAction()); ?>" 
method="<?php echo $this->escape($this->form->getMethod()) ?>" enctype="<?php echo $this->escape($this->form->getEnctype()); ?>">
<input type="hidden" name="date_default" id="date_default" value="<?php echo date('Y-m-d'); ?>" />

<table cellpadding="0" cellspacing="0" class="tablesorter">
	<thead>
		<tr>
			<th>Date</th>			
			<th>Hours</th>
			<th>Company</th>
			<th style="padding-right:20px;">Project</th>
			<th style="padding-right:20px;">Task</th>
			<th style="padding-right:20px;">Billable</th>
			<th>Description</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td style="padding-top:15px;"><?php echo $this->form->date; ?></td>
			<td style="padding-top:15px;"><?php echo $this->form->hours; ?></td>
			<td style="padding-top:15px;"><?php echo $this->form->company_id; ?></td>
			<td style="padding-top:15px;"><?php echo $this->form->project_id; ?></td>
			<td style="padding-top:15px;"><div id="tasks"><?php echo $this->form->task_id; ?></div></td>
			<td style="padding-top:15px;"><?php echo $this->form->billable; ?></td>
			<td style="padding-top:15px;"><?php echo $this->form->description; ?></td>
			<td><input type="submit" class="submit" value="Submit" /></td>
		</tr>
	</tbody>
</table>

</form>