<div class="content_headers" style="padding-top:0px;">
	<div class="user_role_header">User Roles</div>
	<div class="actions">
		<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'roles', 'page' => 'main'), null, TRUE); ?>" rel="facebox" title="About User Roles">
			<?php echo $this->InteractIcon('help', 'About User Roles');?>
			<div class="action_text">Help</div>
		</a>
	</div>	
	<?php if($this->CheckPermission('manage_roles')):?>
	<div class="actions">
		<a href="<?php echo $this->url('roles/add', array('module' => 'pm','controller' => 'roles','action'=>'add'), null, TRUE); ?>" title="Add User Role">
			<?php echo $this->InteractIcon('add', 'Add User Role');?>
			<div class="action_text">Add User Role</div>
		</a>
	</div>
	<?php endif; ?>		
</div>
<?php 
if($this->roles):

	$options = array('roles' => $this->roles, 'enable_actions' => 'yes', 'facebox' => 'yes');
	echo $this->partial('pm/roles/partials/roles', $options);

else: ?>

<div class="information png_bg">There aren't roles added yet. Want to <a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'roles','action'=>'add'), null, TRUE); ?>">add</a> one?.</div>

<?php endif; ?>