<div class="content_headers" style="padding-top:0px;">

	<div class="user_role_header">View User Role: <?php echo $this->role['name']; ?></div>
		<div class="actions">
			<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'roles', 'page' => 'view'), null, TRUE); ?>" rel="facebox" title="Add Project">
				<?php echo $this->InteractIcon('help', 'About User Roles');?>
				<div class="action_text">Help</div>
			</a>
		</div>	
		<?php if($this->CheckPermission('manage_roles')):?>
		<div class="actions">
			<a href="<?php echo $this->url('roles/remove', array('role_id' => $this->role['id']), null, TRUE); ?>" title="Delete">
				<?php echo $this->InteractIcon('cross', 'Delete');?>
				<div class="action_text">Delete</div>
			</a>
		</div>		
		<div class="actions">
			<a href="<?php echo $this->url('roles/edit', array('role_id' => $this->role['id']), null, TRUE); ?>" title="Edit">
				<?php echo $this->InteractIcon('pencil', 'Edit');?>
				<div class="action_text">Edit</div>
			</a>
		</div>
		<?php endif; ?>		
</div>

<div class="item_details">
    <div class="items">
    	<p>
			<span class="bold">Last Modified:</span> <?php echo $this->RelativeDate($this->role['last_modified']); ?><br />
			<span class="bold">Created Date:</span> <?php echo $this->RelativeDate($this->role['created_date']); ?><br />
    	</p>
    </div>
</div>

<br clear="all" />

<?php if($this->role['description'] != ''): ?>
<h2>Description:</h2>
<p><?php echo nl2br($this->role['description']); ?></p>
<?php endif; ?>

<?php 
if($this->permissions): 
?>
<div class="content_headers">
	<div class="permissions_header">Permissions</div>	
	<div class="actions">
		<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'roles', 'page' => 'permissions'), null, TRUE); ?>" rel="facebox" title="Add Project">
			<?php echo $this->InteractIcon('help', 'About Role Permissions');?>
			<div class="action_text">Help</div>
		</a>
	</div>	
</div>
<?php 
	$options = array('permissions' => $this->permissions, 'role_permissions' => $this->role_permissions);
	echo $this->partial('pm/roles/partials/permissions', $options);
endif; ?>

<div class="content_headers">
	<div class="user_header">Users</div>
	<div class="actions">
		<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'roles', 'page' => 'users'), null, TRUE); ?>" rel="facebox" title="Add Project">
			<?php echo $this->InteractIcon('help', 'About Role Users');?>
			<div class="action_text">Help</div>
		</a>
	</div>		
</div>
<?php 
if($this->users):
	$options = array('users' => $this->users);
	echo $this->partial('pm/users/partials/users', $options); 
else: 
?>
<div class="information png_bg">There aren't any users added to this role yet.</div>
<?php endif; ?>