<table cellpadding="0" cellspacing="0" class="<?php echo ($this->tableclass) ? $this->tableclass : 'tablesorter'; ?>" id="<?php echo ($this->tableid) ? $this->tableid : 'moji_permissions'; ?>">
	<thead>
		<tr>
			<th>Permission</th>
			<th>Area</th>
			<th>Allowed</th>
		</tr>
	</thead>
	<tbody>
		<?php
		$i = 0;
		foreach($this->permissions as $perm)
		{
		?>
		<tr>
			<td><?php echo $this->_('permission_'.$perm['name'], 'pm'); ?></td>
			<td><?php echo ucfirst($perm['site_area']); ?></td>
			<td>
			<?php 
			if(is_array($this->role_permissions) && in_array($perm['id'], $this->role_permissions))
			{
				echo $this->InteractIcon('tick', 'Enabled');
			}
			else
			{
				echo $this->InteractIcon('cross', 'Disabled');
			}
			?>
			</td>
		</tr>
		<?php 
		}
		?>
	</tbody>
</table>