<div class="content_headers" style="padding-top:0px;">
	<div class="users_header">Users</div>	
</div>
<dl>
	<dt><a href="<?php echo $this->url('users', array('module' => 'pm','controller' => 'users','action'=>'index'), null, TRUE); ?>">Users</a></dt>
	<dd>Add new users or update existing MojiTrac users.</dd>
	<dt><a href="<?php echo $this->url('roles', array('module' => 'pm','controller' => 'roles','action'=>'index'), null, TRUE); ?>">Roles</a></dt>
	<dd>Decide who can, and can not, do certain activities within MojiTrac.</dd>
</dl>
<br clear="all" />
