<div class="content_headers" style="padding-top:0px;">
	<div class="docs_header">About Time Tracker</div>
</div>
<p>
The Time Tracker allows you to log project & task hours, update progress and manage your 
workload to indicate the amount of work hours spent.
<br /><br />
Simply click onto any day to add time or see previous time entries for that day.
<br /><br />
The calendar view also gives you visibility into all the projects for which you have logged time, 
</p>

<h4>Actions</h4>

<p>
<?php echo $this->InteractIcon('chart', 'Report');?> Time report for the month being viewed.
</p>